package cli

// --- Example blocks for each command ---

var rootExamples = FormatExamples(
	"# Scan a single URL for vulnerabilities",
	"xevon scan -t https://example.com",
	"# Scan targets from a file with specific modules",
	"xevon scan -T targets.txt -m xss-reflected,sqli-error",
	"# Scan an OpenAPI specification",
	"xevon scan -T openapi.yaml -I openapi",
	"# Pipe URLs from stdin",
	"cat urls.txt | xevon scan",
	"# Use a scanning strategy preset",
	"xevon scan -t https://example.com --strategy deep",
	"# Run content discovery before scanning",
	"xevon scan -t https://example.com --discover",
	"# Stateless scan: write findings to a file using a throwaway database",
	"xevon scan --stateless -t https://example.com --format jsonl -o findings.jsonl",
	"# Run a single scan phase",
	"xevon run dynamic-assessment -t https://example.com",
	"# Scan a raw HTTP request piped from stdin",
	"cat request.txt | xevon scan-request",
	"",
	"# Start the API server (uses auto-generated key from config)",
	"xevon server",
	"# Start the server without authentication (local use only)",
	"xevon server -A",
	"",
	"# Ingest HTTP traffic into the database",
	"cat urls.txt | xevon ingest",
	"# Ingest an OpenAPI spec to a remote server",
	"xevon ingest -s http://server:9002 -i api.yaml -I openapi",
	"",
	"# List all scanner modules",
	"xevon module ls",
	"# Search modules by keyword",
	"xevon module ls xss",
	"",
	"# Agentic scan: autonomous end-to-end AI scan of a target",
	"xevon agent autopilot -t https://example.com/api",
	"# Agentic scan: AI source-code security audit of a repo",
	"xevon agent audit --source .",
	"",
	"# View configuration",
	"xevon config ls",
	"# Browse recorded HTTP traffic",
	"xevon traffic",
	"# Database statistics",
	"xevon db stats --detailed",
)

var scanExamples = FormatExamples(
	"# Scan a single URL",
	"xevon scan -t https://example.com",
	"# Scan multiple targets from file",
	"xevon scan -T targets.txt",
	"# Read targets from stdin",
	"cat urls.txt | xevon scan",
	"",
	"# Run specific modules only (fuzzy match on ID/name)",
	"xevon scan -t https://example.com -m xss-reflected,sqli-error",
	"# Filter modules by tag",
	"xevon scan -t https://example.com --module-tag spring --module-tag injection",
	"# With custom headers and proxy",
	`xevon scan -t https://example.com -H "Authorization: Bearer token" --proxy http://127.0.0.1:8080`,
	"",
	"# Scan OpenAPI spec (auto-detects format)",
	"xevon scan -i openapi.yaml -t https://api.example.com",
	"# Scan Burp Suite export",
	"xevon scan -i burp-export.xml -I burp",
	"# Scan HAR file",
	"xevon scan -i traffic.har -I har",
	"",
	"# Use a scanning strategy preset (lite, balanced, deep)",
	"xevon scan -t https://example.com --strategy deep",
	"# Use native scan intensity presets (quick, balanced, deep)",
	"xevon scan -t https://example.com --intensity quick",
	"xevon scan -t https://example.com --intensity balanced",
	"xevon scan -t https://example.com --intensity deep",
	"# Use a scanning profile (quick, standard, full)",
	"xevon scan -t https://example.com --scanning-profile quick",
	"# Override max scan duration",
	"xevon scan -t https://example.com --scanning-max-duration 2h",
	"# Adjust concurrency and rate limit",
	"xevon scan -T targets.txt -c 100 --rate-limit 200 --max-per-host 5",
	"",
	"# Phase isolation: run only one phase",
	"xevon scan -t https://example.com --only discovery",
	"xevon scan -t https://example.com --only known-issue-scan",
	"xevon scan -t https://example.com --only dynamic-assessment",
	"# Skip specific phases",
	"xevon scan -t https://example.com --skip discovery,spidering",
	"",
	"# Run content discovery before scanning",
	"xevon scan -t https://example.com --discover",
	"# Discovery with custom fuzz wordlist",
	"xevon scan -t https://example.com --discover --fuzz-wordlist ~/.xevon/wordlists/fuzz.txt",
	"# Run browser-based spidering",
	"xevon scan -t https://example.com --spider --browsers 2",
	"# External intelligence harvesting",
	"xevon scan -t https://example.com --external-harvest",
	"",
	"# KnownIssueScan phase: filter Nuclei templates by tags and severity",
	"xevon scan -t https://example.com --known-issue-scan-tags cve,misconfig --known-issue-scan-severities critical,high",
	"# KnownIssueScan with custom templates directory",
	"xevon scan -t https://example.com --known-issue-scan-templates-dir ~/my-templates",
	"",
	"# Load custom JavaScript extensions",
	"xevon scan -t https://example.com --ext custom-check.js",
	"# Load all extensions from a directory",
	"xevon scan -t https://example.com --ext-dir ./my-extensions",
	"# Run only extensions (skip built-in modules)",
	"xevon scan -t https://example.com --only extension --ext custom-check.js",
	"",
	"# Output as JSONL",
	"xevon scan -t https://example.com -j",
	"# Generate HTML report",
	"xevon scan -t https://example.com --format html -o report.html",
	"# Write findings to file",
	"xevon scan -t https://example.com -o findings.jsonl",
	"# Stateless scan with JSONL and HTML output",
	"xevon scan --stateless -t https://example.com --format jsonl,html -o scan-output",
	"# Stateless scan: omit raw request/response bytes to keep the JSONL small",
	"xevon scan --stateless -t https://example.com --format jsonl -o sample.jsonl --omit-response",
	"# Stateless multi-target: all targets in one unified output file",
	"xevon scan -S -T targets.txt --format jsonl -o unify-output",
	"# Stateless multi-target: one output file per host (unify-output-<host>.jsonl)",
	"xevon scan -S -T targets.txt --format jsonl -o unify-output --split-by-host",
	"",
	"# Scope all operations to a project",
	"xevon scan -t https://example.com --project-name my-project",
	"# Use OAST callback URL for out-of-band detection",
	"xevon scan -t https://example.com --oast-url https://interact.sh/abc123",
)

var serverExamples = FormatExamples(
	"# Start server (uses auto-generated API key from config)",
	"xevon server",
	"# Start server without authentication (local use only)",
	"xevon server -A",
	"# Start on a custom port",
	"xevon server --service-port 8080",
	"# Bind to localhost only",
	"xevon server --host 127.0.0.1",
	"",
	"# Enable the transparent HTTP ingestion proxy",
	"xevon server --ingest-proxy-port 9003",
	"# Add a secondary ingest key",
	"xevon server --alternative-ingest-key my-secondary-key",
	"",
	"# Auto-scan ingested traffic as it arrives",
	"xevon server --scan-on-receive",
	"# Scan on receive with specific modules and concurrency",
	"xevon server --scan-on-receive -m xss-reflected,sqli-error -c 50",
	"# Scan on receive with more catchup workers",
	"xevon server --scan-on-receive --catchup-threads 8",
	"# Scan on receive without background catchup scan",
	"xevon server --scan-on-receive --disable-catchup",
	"",
	"# Write findings to a file",
	"xevon server --scan-on-receive -o findings.jsonl",
	"# Increase in-memory queue capacity",
	"xevon server --mem-buffer 50000",
	"",
	"# Read-only mode (no scanning, ingestion, or agent endpoints)",
	"xevon server --view-only",
	"# Disable agent endpoints and warm session pooling",
	"xevon server --no-agent",
	"# Disable only warm session pooling",
	"xevon server --disable-warm-session",
	"# Disable Swagger UI",
	"xevon server --no-swagger",
	"",
	"# Production-like setup: localhost, proxy, scan on receive, custom port",
	"xevon server --host 127.0.0.1 --service-port 8080 --ingest-proxy-port 8081 --scan-on-receive",
)

var ingestExamples = FormatExamples(
	"# --- URL inputs ---",
	"# URL list via stdin (line-by-line, streamed)",
	"cat urls.txt | xevon ingest",
	"# URL list via -i file",
	"xevon ingest -i targets.txt",
	"# Single URL via -t",
	"xevon ingest -t https://example.com/api/v1",
	"",
	"# --- Raw HTTP request (auto-detected; response is fetched live) ---",
	"# Stdin",
	"cat request.txt | xevon ingest",
	"# File",
	"xevon ingest -i request.txt",
	"# Skip the live refetch entirely — store the request as-is",
	"cat request.txt | xevon ingest --disable-fetch-response",
	"",
	"# --- Burp request+response pair (auto-detected by '***' separator) ---",
	"# Stdin: response is preserved as-is, no refetch",
	"cat burp-pair.txt | xevon ingest",
	"# File",
	"xevon ingest -i burp-pair.txt",
	"# Pin the format explicitly to skip auto-detect",
	"xevon ingest -i capture.txt -I burpraw",
	"",
	"# --- curl command (auto-detected) ---",
	"# Piped from a file (a leading '$ ' prompt is stripped)",
	"cat command.sh | xevon ingest",
	"# Inline",
	"echo \"curl -X POST https://api.example.com/login -d 'u=a'\" | xevon ingest",
	"",
	"# --- Spec & structured formats ---",
	"# OpenAPI (uses spec server URLs)",
	"xevon ingest -i openapi.yaml --spec-url",
	"# OpenAPI with custom base URL and headers",
	"xevon ingest -i api.yaml -I openapi -t https://api.example.com --spec-header 'Authorization: Bearer xxx'",
	"# HAR / Burp XML / Postman / Nuclei output",
	"xevon ingest -i traffic.har",
	"xevon ingest -i burp-state.xml -I burpxml",
	"",
	"# --- Pipelines ---",
	"# Ingest then scan the new records (-S = scan-on-receive)",
	"cat burp-pair.txt | xevon ingest -S -m xss,sqli",
	"# JSON summary for scripting",
	"cat burp-pair.txt | xevon ingest --json",
	"",
	"# --- Remote ingestion (push to a running xevon server) ---",
	"export XEVON_API_KEY=my-key",
	"cat urls.txt | xevon ingest -s https://xevon.example.com",
	"xevon ingest -s https://xevon.example.com -i api.yaml -I openapi -t https://api.example.com",
)

var moduleExamples = FormatExamples(
	"# List all available modules",
	"xevon module ls",
	"# Search modules by keyword",
	"xevon module ls xss",
	"# List only active (fuzzing) modules",
	"xevon module ls --type active",
	"# Show only enabled modules",
	"xevon module ls --list-enabled",
	"# Enable modules matching a keyword",
	"xevon module enable sqli",
	"# Disable a specific module by exact ID",
	"xevon module disable sqli-error-based --id",
)

var moduleLsExamples = FormatExamples(
	"# List all modules",
	"xevon module ls",
	"# List active modules only",
	"xevon module ls --type active",
	"# List passive modules only",
	"xevon module ls --type passive",
	"# Show only enabled modules",
	"xevon module ls --list-enabled",
)

var moduleEnableExamples = FormatExamples(
	"# Enable all modules matching 'xss'",
	"xevon module enable xss",
	"# Enable a specific module by exact ID",
	"xevon module enable sqli-error-based --id",
)

var moduleDisableExamples = FormatExamples(
	"# Disable all modules matching 'xss'",
	"xevon module disable xss",
	"# Disable a specific module by exact ID",
	"xevon module disable sqli-error-based --id",
)

var configExamples = FormatExamples(
	"# View all current settings",
	"xevon config ls",
	"# Filter settings by section",
	"xevon config ls server",
	"xevon config ls database",
	"# Set a configuration value",
	"xevon config set notify.enabled true",
	"xevon config set database.driver postgres",
	"xevon config set server.service_port 8080",
	"# Reset everything to defaults",
	"xevon config clean",
)

var configLsExamples = FormatExamples(
	"# Show all settings (sensitive values are redacted)",
	"xevon config ls",
	"# Use 'view' alias",
	"xevon config view",
	"# Filter by section",
	"xevon config ls notify",
	"xevon config ls database.sqlite",
	"# Filter with a glob pattern",
	"xevon config view 'kno*'",
	"# Reveal redacted secrets (API keys, tokens, passwords)",
	"xevon config ls --force",
	"xevon config ls notify -F",
)

var configSetExamples = FormatExamples(
	"# Enable notifications",
	"xevon config set notify.enabled true",
	"# Change database driver",
	"xevon config set database.driver postgres",
	"# Set notification severities",
	"xevon config set notify.severities high,critical",
)

var configCleanExamples = FormatExamples(
	"# Reset xevon to clean state (with confirmation)",
	"xevon config clean",
	"# Skip confirmation prompt",
	"xevon config clean -F",
)

var dbListExamples = FormatExamples(
	"# List recent records",
	"xevon db list",
	"# Filter by host",
	"xevon db list --host example.com",
	"# Filter by method and status",
	"xevon db list --method GET,POST --status 200,302",
	"# Tree view",
	"xevon db list --tree",
	"# Show raw HTTP request/response",
	"xevon db list --raw --host example.com -n 5",
	"# Search across URLs and headers",
	`xevon db list --search "admin" --from 2025-01-01`,
	"# Filter by scan session",
	"xevon db list --scan-uuid my-scan",
	"# List all database tables",
	"xevon db list --list-tables",
	"# Show columns for a table",
	"xevon db list findings --list-columns",
	"# List findings table",
	"xevon db list findings",
	"# List any table by name",
	"xevon db list scopes -n 10",
)

var dbStatsExamples = FormatExamples(
	"# Show database statistics",
	"xevon db stats",
	"# Detailed stats with top hosts",
	"xevon db stats --detailed",
	"# Stats for a specific scan",
	"xevon db stats --scan-uuid my-scan",
)

var dbExportExamples = FormatExamples(
	"# Export findings as JSONL (default)",
	"xevon db export",
	"# Export as CSV to file",
	"xevon db export -f csv -o findings.csv",
	"# Export specific host as JSON",
	"xevon db export -f json --host example.com",
	"# Export raw HTTP traffic",
	"xevon db export -f raw --host example.com -o traffic.txt",
)

var dbCleanExamples = FormatExamples(
	"# Preview what would be deleted (dry run)",
	"xevon db clean --host example.com --dry-run",
	"# Delete records older than a date",
	"xevon db clean --before 2025-01-01",
	"# Delete records for a specific scan",
	"xevon db clean --scan-uuid old-scan -F",
	"# Delete all records and reclaim space",
	"xevon db clean --all -F --vacuum",
	"# Clean orphaned findings",
	"xevon db clean --orphans -F",
)

var trafficExamples = FormatExamples(
	"# Browse recent traffic",
	"xevon traffic",
	"# Fuzzy search across URLs, hosts, methods",
	"xevon traffic admin",
	`xevon traffic "api/v2"`,
	"# Tree view",
	"xevon traffic tree",
	"xevon traffic --tree",
	"# Filter by status and method",
	"xevon traffic --status 200,302 --method GET",
	"# Select specific columns",
	"xevon traffic --columns uuid,method,path,status,size",
	"# Exclude columns from default set",
	"xevon traffic --exclude-columns scan_id,time",
	"# Show raw request/response",
	"xevon traffic --raw --host example.com -n 5",
	"# JSON output",
	"xevon traffic -j",
)

var trafficReplayExamples = FormatExamples(
	"# Replay requests matching a search term",
	"xevon traffic replay admin",
	"# Replay filtered by host",
	"xevon traffic replay --host example.com --limit 5",
	"# Replay and replace stored responses",
	"xevon traffic replay --host example.com --in-replace",
	"# Replay through a proxy",
	"xevon traffic replay admin --proxy http://127.0.0.1:8080",
)

var scopeViewExamples = FormatExamples(
	"# Show all scope rules",
	"xevon scope view",
	"# Filter by component",
	"xevon scope view host",
	"xevon scope view status_code",
)

var runExamples = FormatExamples(
	"# Run content discovery phase",
	"xevon run discover -t https://example.com",
	"# Discovery with custom fuzz wordlist",
	"xevon run discover -t https://example.com --fuzz-wordlist ~/.xevon/wordlists/fuzz.txt",
	"# Run browser-based spidering",
	"xevon run spidering -t https://example.com",
	"# Run known-issue-scan phase",
	"xevon run known-issue-scan -t https://example.com",
	"# Run known-issue-scan with custom Nuclei template tags",
	"xevon run known-issue-scan -t https://example.com --known-issue-scan-tags cve,misconfig --known-issue-scan-severities critical,high",
	"# Run dynamic-assessment with specific modules",
	"xevon run dynamic-assessment -t https://example.com -m xss-reflected",
	"# Run dynamic-assessment with module tag filter",
	"xevon run dynamic-assessment -t https://example.com --module-tag spring",
	"# Run external intelligence harvesting",
	"xevon run external-harvest -t https://example.com",
	"# Run only JavaScript extensions",
	"xevon run extension -t https://example.com --ext custom-check.js",
	"",
	"# Use a scanning profile for the phase",
	"xevon run discover -t https://example.com --scanning-profile full",
	"# Use native scan intensity for the phase",
	"xevon run dynamic-assessment -t https://example.com --intensity deep",
	"# Override scan duration",
	"xevon run discover -t https://example.com --scanning-max-duration 2h",
	"# Run with custom headers",
	`xevon run dynamic-assessment -t https://example.com -H "Authorization: Bearer token"`,
	"# Scope to a specific project",
	"xevon run known-issue-scan -t https://example.com --project-name my-project",
	"",
	"# Stateless run: write the phase output to a file using a throwaway database",
	"xevon run discovery --stateless -t https://example.com --format jsonl -o sample.jsonl",
	"# Stateless run: omit raw HTTP request/response bytes for a much smaller file",
	"xevon run discovery --stateless -t https://example.com --format jsonl -o sample.jsonl --omit-response",
	"",
	"# Short alias",
	"xevon r discovery -t https://example.com",
	"# Phase aliases: deparos=discovery, discover=discovery, spitolas=spidering, audit/dast/assessment=dynamic-assessment, ext=extension",
	"xevon run deparos -t https://example.com",
	"xevon run dast -t https://example.com",
)

var agentExamples = FormatExamples(
	"# List configured agent backends",
	"xevon agent --list-agents",
	"# List available prompt templates",
	"xevon agent --list-templates",
	"# Olium — direct interactive (TUI) access to the in-process agent",
	"xevon agent olium",
	`xevon agent olium -p "list the routes in pkg/server"`,
	"# Autopilot — agentic scan, autonomous end-to-end",
	"xevon agent autopilot -t https://example.com/api",
	"xevon agent autopilot -t https://example.com --source ./src",
	`xevon agent autopilot "scan VAmPI source at ~/src/VAmPI on localhost:3005"`,
	"# Swarm — AI-guided scanning with module selection and triage",
	`xevon agent swarm --input "https://example.com/api/users?id=1"`,
	"xevon agent swarm -t https://example.com --source ./src --discover",
	"# Audit — unified driver: audit then piolium under one AgenticScan",
	"xevon agent audit --source .",
	"xevon agent audit --driver piolium --source ./backend --mode lite",
	"# Audit — foreground source-code security audit (single driver)",
	"xevon agent audit --mode deep --source .",
	"xevon agent audit --mode lite --source https://github.com/org/repo",
	"# Piolium — Pi-native foreground security audit (single driver)",
	"xevon agent audit --driver=piolium --mode balanced --source .",
	"# Query — single-shot prompt (code review, secret detection, etc.)",
	"xevon agent query --source ./myapp --prompt-template security-code-review",
)

var agenticScanExamples = FormatExamples(
	"# Send a prompt to the agent",
	`xevon agent query --prompt "Analyze this code for SQL injection: SELECT * FROM users WHERE id = $input"`,
	"# Pipe prompt from stdin",
	`echo "Find XSS vulnerabilities in this JavaScript" | xevon agent query --stdin`,
	"# Tag the AgenticScan DB row with a custom label",
	`xevon agent query --prompt "hello" --agent-label code-review`,
	"# Save output to file",
	`xevon agent query --prompt "Review this code" --output review.json`,
)

var exportExamples = FormatExamples(
	"# Export all data (HTTP records, findings, scans, modules, etc.)",
	"xevon export --format jsonl -o full-export.jsonl",
	"# Export findings and HTTP records",
	"xevon export --format jsonl --only findings,http",
	"# Export HTTP records as HTML report",
	"xevon export --format html -o report.html",
	"# Export a bundle archive (.tar.gz with export.jsonl, report.html, manifest.json)",
	"xevon export --format bundle -o results.tar.gz",
	"# Bundle and include a specific agentic scan's session directory",
	"xevon export --format bundle --scan-uuid <scan-uuid> -o results.tar.gz",
	"# Bundle multiple agentic scan sessions into one archive",
	"xevon export --format bundle --scan-uuid <uuid-1> --scan-uuid <uuid-2> -o bundle.tar.gz",
	"# Bundle and upload directly to cloud storage with {ts} placeholder",
	"xevon export --format bundle --scan-uuid <scan-uuid> -o gs://<project-uuid>/bundles/run-{ts}.tar.gz",
	"# Scope export to a specific project (overrides active project / $XEVON_PROJECT_UUID)",
	"xevon export --project-uuid <project-uuid> --format jsonl -o project-export.jsonl",
	"# Bundle a specific project's data alongside its agent session",
	"xevon export --project-uuid <project-uuid> --format bundle --scan-uuid <scan-uuid> -o project-bundle.tar.gz",
	"# Export findings only for a specific project as HTML",
	"xevon export --project-uuid <project-uuid> --format html --only findings -o findings.html",
	"# Export directly to cloud storage (gs:// URL)",
	"xevon export --format jsonl -o gs://<project-uuid>/exports/full.jsonl",
	"# Use {ts} for an automatic UTC timestamp (e.g. 2026-04-26T14-05-30Z)",
	"xevon export --format html -o gs://<project-uuid>/reports/scan-{ts}.html",
	"xevon export --format jsonl -o gs://<project-uuid>/exports/data-{ts}.jsonl",
	"# {project-uuid} expands to the active project; combine with {ts}",
	"xevon export --format html -o gs://{project-uuid}/reports/scan-{ts}.html",
)

var scopeSetExamples = FormatExamples(
	"# Exclude internal hosts",
	`xevon scope set host.exclude "*.internal.com,admin.*"`,
	"# Only scan API paths",
	`xevon scope set path.include "/api/*,/v2/*"`,
	"# Exclude static file responses",
	`xevon scope set response_content_type.exclude "image/*,font/*"`,
	"# Exclude error status codes from scanning",
	`xevon scope set status_code.exclude "404,500,502,503"`,
)

var dbExamples = FormatExamples(
	"# Show database statistics",
	"xevon db stats",
	"# List recent HTTP records",
	"xevon db list",
	"# List findings",
	"xevon db list findings",
	"# Export findings as JSONL",
	"xevon db export -f jsonl -o findings.jsonl",
	"# Preview a clean by host (dry-run)",
	"xevon db clean --host example.com --dry-run",
	"# Seed sample data for development",
	"xevon db seed",
)

var dbSeedExamples = FormatExamples(
	"# Insert sample hosts, scans, records, and findings",
	"xevon db seed",
	"# Seed against a specific SQLite file",
	"xevon db seed --db /tmp/playground.sqlite",
)

var scopeExamples = FormatExamples(
	"# View all scope rules (default action)",
	"xevon scope",
	"# View only a specific component",
	"xevon scope view host",
	"# Set a rule via the set subcommand",
	`xevon scope set host.exclude "*.internal.com"`,
)

var agentSessionExamples = FormatExamples(
	"# List recent agent run sessions",
	"xevon agent session",
	"# List only autopilot runs, max 20",
	"xevon agent session --mode autopilot -n 20",
	"# Show details of a specific session",
	"xevon agent session 9b2f...",
	"# Show full raw output instead of the tail",
	"xevon agent session 9b2f... --full",
)

var doctorExamples = FormatExamples(
	"# Run all readiness checks",
	"xevon doctor",
	"# Verbose mode with full diagnostics",
	"xevon doctor -v",
	"# Auto-install/fix every failing check",
	"xevon doctor --fix",
	"# Fix only specific components (focused output — just those checks)",
	"xevon doctor --fix --only nuclei,chrome",
	"# Other fixable components: bun, claude, agent-browser, pi, piolium",
	"xevon doctor --fix --only claude",
)

var extensionsParentExamples = FormatExamples(
	"# List loaded extensions",
	"xevon extensions",
	"# Filter by substring",
	"xevon extensions xss",
	"# Show extension API reference",
	"xevon extensions docs",
	"# Install starter presets into ~/.xevon/extensions/",
	"xevon extensions preset",
	"# Lint an extension file",
	"xevon extensions lint ./my-check.js",
)

var extensionsLsExamples = FormatExamples(
	"# List every extension",
	"xevon extensions ls",
	"# Filter by id/name/description",
	"xevon extensions ls auth",
	"# Active extensions only",
	"xevon extensions ls --type active",
	"# Verbose: include long description and confirmation criteria",
	"xevon extensions ls -v",
)

var extensionsDocsExamples = FormatExamples(
	"# List every namespace and function",
	"xevon extensions docs",
	"# Drill into a specific function",
	"xevon extensions docs http.request",
	"# Include full usage examples",
	"xevon extensions docs --example",
)

var extensionsPresetExamples = FormatExamples(
	"# Install all starter presets",
	"xevon extensions preset",
	"# Install only a single named preset",
	"xevon extensions preset jwt-none",
)

var findingExamples = FormatExamples(
	"# Browse all findings interactively",
	"xevon finding",
	"# Fuzzy search by term",
	"xevon finding xss",
	"# Filter by host and severity",
	"xevon finding --host example.com --severity high,critical",
	"# Show raw request/response for matched findings",
	"xevon finding --raw -n 5",
	"# JSONL output",
	"xevon finding -j",
)

var findingLoadExamples = FormatExamples(
	"# Import findings from a JSONL file",
	"xevon finding load findings.jsonl",
	"# Pipe agent output (markdown-wrapped JSON) from stdin",
	"xevon agent query --prompt-template review | xevon finding load",
	"# Import a single JSON object",
	"xevon finding load report.json",
)

var logExamples = FormatExamples(
	"# List recent scan and agent sessions",
	"xevon log",
	"# Stream logs for a specific session UUID",
	"xevon log 9b2f...",
	"# Open the interactive picker",
	"xevon log --tui",
)

var logLsExamples = FormatExamples(
	"# List every available session log",
	"xevon log ls",
)

var projectCreateExamples = FormatExamples(
	"# Create a project",
	`xevon project create my-app --description "Main web app"`,
	"# Create with access control in one line",
	"xevon project create my-app --allow @acme.com --allow alice@partner.io",
)

var projectListExamples = FormatExamples(
	"# List all projects (interactive picker if a TTY)",
	"xevon project ls",
	"# Machine-readable output",
	"xevon project ls --json",
)

var projectUseExamples = FormatExamples(
	"# Set the active project for the current shell",
	"eval $(xevon project use 9b2f-...)",
)

var projectConfigExamples = FormatExamples(
	"# Show the active project's config file path",
	"xevon project config",
	"# Show config path for a specific project",
	"xevon project config 9b2f-...",
)

var sessionExamples = FormatExamples(
	"# List session auth configs",
	"xevon auth list",
	"# Load session configs from a YAML file",
	"xevon auth load sessions.yaml",
	"# Lint a session config file",
	"xevon auth lint sessions.yaml",
	"# Generate a TOTP code for 2FA flows",
	"xevon auth totp --secret JBSWY3DPEHPK3PXP",
)

var sessionLsExamples = FormatExamples(
	"# List all session configs for the active project",
	"xevon auth list",
	"# Filter by hostname",
	"xevon auth list --host api.example.com",
	"# JSON output",
	"xevon auth list -j",
)

var sessionTotpExamples = FormatExamples(
	"# Generate a code from a base32 secret",
	"xevon auth totp --secret JBSWY3DPEHPK3PXP",
)

var strategyExamples = FormatExamples(
	"# Show strategies, phases, intensities, and agent modes",
	"xevon strategy",
	"# Use a strategy in a scan",
	"xevon scan -t https://example.com --strategy deep",
	"# Set the default strategy in config",
	"xevon config set scanning_strategy.default_strategy balanced",
)

var versionExamples = FormatExamples(
	"# Show version, build, and license info",
	"xevon version",
	"# JSON output for tooling",
	"xevon version -j",
)

var oliumExamples = FormatExamples(
	"# Empty interactive session",
	"xevon agent olium",
	"# Seed the session with a first prompt, stay interactive",
	`xevon agent olium "audit pkg/auth for hardcoded secrets"`,
	"# Pipe a prompt in, stay interactive",
	"cat task.txt | xevon agent olium",
	"# One-shot, non-interactive",
	`xevon agent olium -p "list the routes in pkg/server"`,
)

var agentAuditExamples = FormatExamples(
	"# Default: audit then piolium under one AgenticScan, balanced mode",
	"xevon agent audit --source .",
	"",
	"# Just piolium (single driver — no audit, no fallback)",
	"xevon agent audit --driver piolium --source ./backend --mode lite",
	"",
	"# Just audit (single driver — equivalent to `agent audit`)",
	"xevon agent audit --driver audit --source ./backend --agent claude",
	"",
	"# Both drivers, deep mode, on a remote git URL with full commit history",
	"xevon agent audit --source git@github.com:org/repo.git --intensity deep",
	"",
	"# Override pi's provider/model for the piolium leg (vertex-anthropic)",
	"xevon agent audit --source ./backend \\",
	"  --pi-provider vertex-anthropic --pi-model claude-opus-4-6",
	"",
	"# Driver-specific mode requires --driver=piolium (or =audit for mock)",
	"xevon agent audit --driver piolium --source ./mono-repo --mode longshot \\",
	"  --plm-longshot-langs python,go --plm-longshot-limit 200",
	"",
	"# Skip the post-pass project-wide findings dedup",
	"xevon agent audit --source ./backend --no-dedup",
	"",
	"# Pull source from a cloud-storage archive",
	"xevon agent audit --source gs://my-bucket/snapshots/repo.tar.gz",
	"",
	"# Interactive — drop into the coding agent with the audit harness",
	"# installed and drive the audit yourself (audit's -i)",
	"xevon agent audit --source . --interactive",
	"# Afterward, import the on-disk audit results and write an HTML report in one step",
	"xevon import ./audit --format html -o audit-report.html",
)

var agentAutopilotExamples = FormatExamples(
	"# Natural language prompt — target, source, and focus auto-extracted",
	`xevon agent autopilot "scan VAmPI source at ~/src/VAmPI on localhost:3005"`,
	`xevon agent autopilot "test auth bypass on https://app.example.com"`,
	"# Scan a target URL",
	"xevon agent autopilot -t https://example.com/api",
	"# Scan with application source code (triggers xevon-audit automatically)",
	"xevon agent autopilot -t https://example.com --source ./src",
	"# Pipe a curl command or raw HTTP request via stdin",
	"curl -s https://example.com/api/users | xevon agent autopilot",
	"cat request.txt | xevon agent autopilot -t https://example.com",
	"# Pass a curl command or raw HTTP as input",
	`xevon agent autopilot --input "curl -X POST -H 'Content-Type: application/json' -d '{\"user\":\"admin\"}' https://example.com/api/login"`,
	"# Focus on specific vulnerability types",
	`xevon agent autopilot -t https://example.com --focus "auth bypass and IDOR"`,
	"# Deep scan with browser and extended limits",
	"xevon agent autopilot -t https://example.com --intensity deep",
	"# Quick CI/PR scan with short timeout",
	"xevon agent autopilot -t https://example.com --source ./src --intensity quick",
	"# Source-aware scan with specific files and custom instructions",
	`xevon agent autopilot -t https://example.com --source ./src --files "routes/api.js,controllers/auth.js" --instruction "Focus on the new payment endpoint"`,
	"# Scan a PR diff for security regressions",
	`xevon agent autopilot -t https://example.com --source ./src --diff "main...feature-branch"`,
	"xevon agent autopilot -t https://example.com --source ./src --last-commits 3",
	"# Use a specific agent backend",
	"xevon agent autopilot -t https://example.com --provider anthropic-api-key",
	"# Enable browser-based auth flow",
	`xevon agent autopilot -t https://example.com --browser --credentials "admin/admin123"`,
	"# Preview the rendered prompt without executing",
	"xevon agent autopilot -t https://example.com --source ./src --dry-run",
	"# Disable xevon-audit when using --source",
	"xevon agent autopilot -t https://example.com --source ./src --audit=off",
)

var agentSwarmExamples = FormatExamples(
	"# Swarm a single URL",
	`xevon agent swarm --input "https://example.com/api/users?id=1"`,
	"# Swarm a curl command",
	`xevon agent swarm --input "curl -X POST -H 'Content-Type: application/json' -d '{\"user\":\"admin\"}' https://example.com/api/login"`,
	"# Pipe a raw HTTP request from stdin",
	"cat request.txt | xevon agent swarm",
	"# Swarm with source code for route discovery",
	"xevon agent swarm -t https://example.com --source ./src",
	"# Source-aware swarm with specific files",
	`xevon agent swarm -t https://example.com --source ./src --files "routes/api.js,controllers/auth.js"`,
	"# Only run source analysis (no scanning)",
	"xevon agent swarm -t https://example.com --source ./src --source-analysis-only",
	"# Focus on a specific vulnerability type",
	`xevon agent swarm --input "https://example.com/search?q=test" --vuln-type sqli`,
	"# Use specific scanner modules",
	`xevon agent swarm --input "https://example.com/api" -m sqli -m xss -m ssti`,
	"# Run discovery+spidering before planning",
	"xevon agent swarm -t https://example.com --discover",
	"# Tag the AgenticScan DB row with a custom label",
	`xevon agent swarm --input "https://example.com" --agent-label api-pentest`,
	"# Swarm a database record",
	"xevon agent swarm --record-uuid abc123-def456",
	"# Add custom instructions to guide the agent",
	`xevon agent swarm --input "https://example.com" --instruction "Focus on auth bypass and IDOR"`,
	"# Load instructions from a file",
	`xevon agent swarm --input "https://example.com" --instruction-file ./pentest-notes.md`,
	"# Skip specific scan phases",
	"xevon agent swarm -t https://example.com --source ./src --skip discovery,spidering",
	"# Limit triage-rescan iterations",
	`xevon agent swarm --input "https://example.com" --max-iterations 1`,
	"# Dry run — render prompts without executing",
	"xevon agent swarm -t https://example.com --source ./src --dry-run",
	"# Show rendered prompts on stderr while executing",
	`xevon agent swarm --input "https://example.com" --show-prompt`,
	"# Quick intensity — fast scan for CI/CD pipelines",
	`xevon agent swarm --input "https://example.com/api/users?id=1" --intensity quick`,
	"# Deep intensity — full discovery, triage, browser, extended duration",
	"xevon agent swarm -t https://example.com --source ./src --intensity deep",
	"# Override a specific setting within an intensity preset",
	"xevon agent swarm -t https://example.com --intensity deep --triage=false",
)

var scanURLExamples = FormatExamples(
	"# Scan a URL directly",
	"xevon scan-url https://example.com/api/users?id=1",
	"# Scan with a specific HTTP method and body",
	`xevon scan-url --method POST --body '{"user":"admin"}' -H 'Content-Type: application/json' https://example.com/api/login`,
	"# Scan with custom headers",
	`xevon scan-url -H 'Authorization: Bearer tok123' -H 'X-Custom: value' https://example.com/api/data`,
	"# Pipe a URL from stdin",
	"echo 'https://example.com/search?q=test' | xevon scan-url",
	"# Pipe a curl command from stdin",
	`echo "curl -X POST -d 'user=admin' https://example.com/login" | xevon scan-url`,
	"# Pipe a raw HTTP request from stdin",
	`printf 'GET /api/users?id=1 HTTP/1.1\r\nHost: example.com\r\n\r\n' | xevon scan-url`,
	"# Run only specific modules",
	"xevon scan-url -m sqli -m xss https://example.com/search?q=test",
	"# Skip passive analysis",
	"xevon scan-url --no-passive https://example.com/api/users",
	"# Enable content discovery before scanning",
	"xevon scan-url --discover https://example.com/",
	"# JSON output for scripting",
	"xevon scan-url --json https://example.com/api/users?id=1",
)

var scanRequestExamples = FormatExamples(
	"# Read a raw HTTP request from a file",
	"xevon scan-request -i request.txt",
	"# Pipe a raw HTTP request from stdin",
	`printf 'POST /api/login HTTP/1.1\r\nHost: example.com\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\nuser=admin&pass=secret' | xevon scan-request`,
	"# Pipe a curl command from stdin (auto-detected)",
	`echo "curl -X POST -H 'Content-Type: application/json' -d '{\"user\":\"admin\"}' https://example.com/api/login" | xevon scan-request`,
	"# Override the target host (useful for raw requests without full URL)",
	"xevon scan-request -i request.txt --target https://staging.example.com",
	"# Scan with specific modules only",
	`printf 'GET /search?q=test HTTP/1.1\r\nHost: example.com\r\n\r\n' | xevon scan-request -m sqli -m xss`,
	"# Skip passive modules",
	"xevon scan-request -i request.txt --no-passive",
	"# Read from a Burp Suite saved request file",
	"xevon scan-request -i burp-request.txt --target https://example.com",
	"# JSON output for scripting",
	"cat request.txt | xevon scan-request --json",
)

var jsExamples = FormatExamples(
	"# From stdin (default — ideal for agent mode)",
	`echo 'xevon.http.get("https://example.com")' | xevon js`,
	"# Inline code",
	`xevon js --code 'xevon.http.get("https://example.com/api/users")'`,
	"# From a file",
	"xevon js --code-file script.js",
	"# With target context",
	`xevon js --target https://example.com --code 'xevon.http.get(TARGET + "/api")'`,
	"# With timeout",
	"xevon js --timeout 60s --code-file long_running.js",
)

var storageExamples = FormatExamples(
	"# List objects in cloud storage for the active project",
	"xevon storage ls",
	"# Upload a local file (default key: ugc/<basename>)",
	"xevon storage upload ./scan-bundle.tar.gz",
	"# Download an object",
	"xevon storage download ugc/scan-bundle.tar.gz -o ./local.tar.gz",
	"# Download a scan result bundle by scan UUID",
	"xevon storage results <scan-uuid>",
	"# Generate a presigned download URL valid for 30 minutes",
	"xevon storage presign --key ugc/scan-bundle.tar.gz --expiry 30m",
	"# Delete one or more objects (skip prompt with -F)",
	"xevon storage rm imports/old-bundle.tar.gz -F",
)

var storageLsExamples = FormatExamples(
	"# List every object stored for the active project",
	"xevon storage ls",
	"# Limit to a sub-prefix (e.g. ugc/, native-scans/, agentic-scans/)",
	"xevon storage ls --prefix ugc/",
	"# Render keys as a directory tree",
	"xevon storage ls --tree",
	"# Machine-readable output",
	"xevon storage ls --json",
)

var storageUploadExamples = FormatExamples(
	"# Upload a local file (stored at ugc/<basename>)",
	"xevon storage upload ./scan-bundle.tar.gz",
	"# Upload with an explicit storage key",
	"xevon storage upload ./report.html --key reports/quarterly.html",
	"# Upload with a Content-Type header set on the object",
	"xevon storage upload ./data.json --content-type application/json",
)

var storageDownloadExamples = FormatExamples(
	"# Stream an object to stdout",
	"xevon storage download ugc/scan-bundle.tar.gz > local.tar.gz",
	"# Write directly to a file",
	"xevon storage download reports/quarterly.html -o ./quarterly.html",
)

var storageResultsExamples = FormatExamples(
	"# Download the result bundle for a scan UUID",
	"xevon storage results 9c1f5e0d-...",
	"# Save to a custom path",
	"xevon storage results 9c1f5e0d-... -o ./results.tar.gz",
)

var storagePresignExamples = FormatExamples(
	"# Generate a download URL (default: GET, 1h validity)",
	"xevon storage presign --key ugc/scan-bundle.tar.gz",
	"# Generate an upload URL valid for 15 minutes",
	"xevon storage presign --key ugc/incoming.bin --method PUT --expiry 15m",
	"# JSON output for scripting",
	"xevon storage presign --key reports/quarterly.html --json",
)

var storageRmExamples = FormatExamples(
	"# Delete a single object (will prompt for confirmation)",
	"xevon storage rm imports/old-bundle.tar.gz",
	"# Delete several objects, skipping the confirmation prompt",
	"xevon storage rm imports/a.tar.gz imports/b.tar.gz -F",
)

var importExamples = FormatExamples(
	"# Import a folder produced by xevon-audit",
	"xevon import ./audit-output/",
	"# Import a folder and also archive it to cloud storage afterwards",
	"xevon import ./audit-output/ --upload",
	"# Import a folder and upload to a custom storage key",
	"xevon import ./audit-output/ --upload-key imports/audit-output.tar.gz",
	"# Import an audit folder and write a report in the same step (replaces import-then-export)",
	"xevon import ./audit-output/ --format html -o audit-report.html",
	"# Same one-step import + export, as Markdown (also: report, pdf)",
	"xevon import ./audit-output/ --format md -o audit-report.md",
	"# Import a JSONL file produced by 'xevon export'",
	"xevon import ./export.jsonl",
	"# Import a generic JSONL scan-results file",
	"xevon import scan-results.jsonl",
	"# Import a compressed archive (.tar.gz, .tgz, or .zip)",
	"xevon import scan-bundle.tar.gz",
	"xevon import findings.zip",
	"# Import directly from cloud storage",
	"xevon import gs://<project-uuid>/imports/audit-output.tar.gz",
)

var initExamples = FormatExamples(
	"# First-time setup",
	"xevon init",
	"# Reinitialize: regenerate config (with new API key) and re-extract presets",
	"xevon init --force",
)

var extensionsEvalExamples = FormatExamples(
	"# Inline code",
	`xevon ext eval 'xevon.log.info("hello")'`,
	"# From a file",
	"xevon ext eval --ext-file script.js",
	"# From stdin",
	`echo 'xevon.utils.md5("hello")' | xevon ext eval --stdin`,
)

var extensionsLintExamples = FormatExamples(
	"# Lint a single JS file",
	"xevon extensions lint my-extension.js",
	"# Lint a YAML extension",
	"xevon extensions lint auth-hook.vgm.yaml",
	"# Lint all extensions in a directory",
	"xevon extensions lint ~/.xevon/extensions/",
	"# Lint from stdin",
	"cat my-extension.js | xevon extensions lint --stdin",
	"# Lint a TypeScript extension",
	"xevon extensions lint my-extension.ts",
)

var sessionLintExamples = FormatExamples(
	"# Lint a session config file",
	"xevon auth lint auth-config.yaml",
	"# Lint a JSON session config",
	"xevon auth lint session-config.json",
	"# Lint from stdin",
	"cat auth-config.yaml | xevon auth lint --stdin",
)

var sessionLoadExamples = FormatExamples(
	"# Load a YAML session config bound to a host",
	"xevon auth load auth-config.yaml --host example.com",
	"# Load an agent-produced session-config.json",
	"xevon auth load ~/.xevon/agent-sessions/<uuid>/session-config.json",
	"# Load without re-validating login flows",
	"xevon auth load sessions.json --no-validate",
	"# Pipe a session config from stdin",
	"cat session-config.json | xevon auth load",
	"# Pipe a raw HTTP login request from stdin",
	"cat login-req.txt | xevon auth load",
	"# Same, but force a name and host",
	"cat login-req.txt | xevon auth load --name admin --host juice-shop.example.com",
)

var projectExamples = FormatExamples(
	"# Create a project",
	`xevon project create my-app --description "Main web app"`,
	"# Create with access control in one line",
	"xevon project create my-app --allow @acme.com --allow alice@partner.io",
	"# List projects",
	"xevon project ls",
	"xevon project ls --json",
	"# Set active project",
	"eval $(xevon project use <uuid>)",
	"# Add/remove access later",
	"xevon project allow <uuid> @newdomain.com user@example.com",
	"xevon project remove-access <uuid> @olddomain.com",
)
